import { SongEntry } from './types';

// Aliases from: https://xn--hckp3ac2l023wu2ve.com/live-music-ryakushou-matome.html
export const LOVELIVE_SUNSHINE_SONGS: SongEntry[] = [
  {
    id: 'A0001',
    name: { jp: '君のこころは輝いてるかい？', kr: '너의 마음은 빛나고 있니?' },
    artist: 'Aqours',
    year: 2015,
    alias: ['키미노 코코로와 카가야이테루카이?', '키미코코'],
  },
  {
    id: 'A0002',
    name: { jp: 'Step! ZERO to ONE', kr: 'Step! ZERO to ONE' },
    artist: 'Aqours',
    year: 2015,
    alias: ['스텝 제로 투 원', '스텝! 제로 투 원', '01', '제로원'],
  },
  {
    id: 'A0003',
    name: { jp: 'Aqours☆HEROES', kr: 'Aqours☆HEROES' },
    artist: 'Aqours',
    year: 2015,
    alias: ['아쿠아 히어로', '히로'],
  },
  {
    id: 'A0004',
    name: { jp: '恋になりたいAQUARIUM', kr: '사랑이 되고 싶은 AQUARIUM' },
    artist: 'Aqours',
    year: 2016,
    alias: ['코이니 나리타이 아쿠아리움', '코이아쿠'],
  },
  {
    id: 'A0005',
    name: { jp: '待ってて愛のうた', kr: '기다려줘 사랑의 노래' },
    artist: 'Aqours',
    year: 2016,
    alias: ['맛떼떼 아이노 우타', '맛떼아이', '맛테아이', '아이우타'],
  },
  {
    id: 'A0006',
    name: { jp: '届かない星だとしても', kr: '닿을 수 없는 별이라 해도' },
    artist: 'Aqours',
    year: 2016,
    alias: ['토도카나이 호시다토 시테모', '토도호시'],
  },
  {
    id: 'A0007',
    name: { jp: '元気全開DAY! DAY! DAY!', kr: '활기전개 DAY! DAY! DAY!' },
    artist: 'CYaRon！',
    year: 2016,
    alias: ['원기전개 DAY! DAY! DAY!', '겡키 젠카이 데이데이데이', 'DDD'],
  },
  {
    id: 'A0008',
    name: { jp: '夜空はなんでも知ってるの？', kr: '밤하늘은 뭐든지 알고 있는 거야?' },
    artist: 'CYaRon！',
    year: 2016,
    alias: ['요조라와 난데모 싯떼루노?', '요조라', '요조싯떼'],
  },
  {
    id: 'A0009',
    name: { jp: 'トリコリコPLEASE!!', kr: '토리코리코PLEASE!!' },
    artist: 'AZALEA',
    year: 2016,
    alias: ['토리코리코 플리즈!!'],
  },
  {
    id: 'A0010',
    name: { jp: 'ときめき分類学', kr: '두근거림 분류학' },
    artist: 'AZALEA',
    year: 2016,
    alias: ['토키메키'],
  },
  {
    id: 'A0011',
    name: { jp: 'Strawberry Trapper', kr: 'Strawberry Trapper' },
    artist: 'Guilty Kiss',
    year: 2016,
    alias: ['스트로베리 트래퍼', '스트토라', '스토토라', '딸기 함정꾼'],
  },
  {
    id: 'A0012',
    name: { jp: 'Guilty Night, Guilty Kiss!', kr: 'Guilty Night, Guilty Kiss!' },
    artist: 'Guilty Kiss',
    year: 2016,
    alias: ['길티 나잇, 길티 키스!', '길티 나잇 길티 키스', '길낫길키', '기루나이', 'GNGK'],
  },
  {
    id: 'A0013',
    name: { jp: '青空Jumping Heart', kr: '푸른 하늘 Jumping Heart' },
    artist: 'Aqours',
    year: 2016,
    alias: ['아오조라 점핑하트', '아오잠', '아오쟘'],
  },
  {
    id: 'A0014',
    name: { jp: 'ハミングフレンド', kr: '허밍 프렌드' },
    artist: 'Aqours',
    year: 2016,
    alias: [],
  },
  {
    id: 'A0015',
    name: { jp: 'ユメ語るよりユメ歌おう', kr: '꿈을 말하기보다 꿈을 노래하자' },
    artist: 'Aqours',
    year: 2016,
    alias: ['유메유메'],
  },
  {
    id: 'A0016',
    name: { jp: 'サンシャインぴっかぴか音頭', kr: '선샤인 반짝반짝 선창' },
    artist: 'Aqours',
    year: 2016,
    alias: ['삐까삐까'],
  },
  {
    id: 'A0017',
    name: { jp: '決めたよHand in Hand', kr: '결정했어 Hand in Hand' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우',
    year: 2016,
    alias: ['키메타요 핸드 인 핸드', '핸인핸', '키메한'],
  },
  {
    id: 'A0018',
    name: { jp: 'ダイスキだったらダイジョウブ！', kr: '정말로 좋아한다면 괜찮을 거야!' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우',
    year: 2016,
    alias: ['다이스키닷타라 다이죠부', '다이다이', '다다다'],
  },
  {
    id: 'A0019',
    name: { jp: '夢で夜空を照らしたい', kr: '꿈으로 밤하늘을 비추고 싶어' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우, 츠시마 요시코, 쿠니키다 하나마루, 쿠로사와 루비',
    year: 2016,
    alias: ['유메요조', '유메테라'],
  },
  {
    id: 'A0020',
    name: { jp: '未熟DREAMER', kr: '미숙 DREAMER' },
    artist: 'Aqours',
    year: 2016,
    alias: ['미숙 드리머'],
  },
  {
    id: 'A0021',
    name: { jp: '想いよひとつになれ', kr: '마음이여 하나가 되어라' },
    artist: '타카미 치카, 마츠우라 카난, 쿠로사와 다이아, 와타나베 요우, 츠시마 요시코, 쿠니키다 하나마루, 오하라 마리, 쿠로사와 루비',
    year: 2016,
    alias: ['오모이요 히토츠니 나레', '오모히토'],
  },
  {
    id: 'A0022',
    name: { jp: 'MIRAI TICKET', kr: 'MIRAI TICKET' },
    artist: 'Aqours',
    year: 2016,
    alias: ['미래 티켓', '미라치케'],
  },
  {
    id: 'A0023',
    name: { jp: 'Pops heartで踊るんだもん！', kr: 'Pops heart로 춤추는걸!' },
    artist: 'Aqours',
    year: 2016,
    alias: ['팝스하트'],
  },
  {
    id: 'A0024',
    name: { jp: '空も心も晴れるから', kr: '하늘도 마음도 맑을 테니까' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우',
    year: 2016,
    alias: ['소라하레'],
  },
  {
    id: 'A0025',
    name: { jp: 'Waku-Waku-Week!', kr: 'Waku-Waku-Week!' },
    artist: '츠시마 요시코, 쿠니키다 하나마루, 쿠로사와 루비',
    year: 2016,
    alias: ['와쿠와쿠위크', 'WWW'],
  },
  {
    id: 'A0026',
    name: { jp: 'Daydream Warrior', kr: 'Daydream Warrior' },
    artist: 'Aqours',
    year: 2016,
    alias: ['데이드림 워리어', '데이워리'],
  },
  {
    id: 'A0027',
    name: { jp: 'G線上のシンデレラ', kr: 'G선상의 신데렐라' },
    artist: '마츠우라 카난, 쿠로사와 다이아, 오하라 마리',
    year: 2017,
    alias: ['지선상의 신데렐라', 'G데렐라'],
  },
  {
    id: 'A0028',
    name: { jp: 'スリリング・ワンウェイ', kr: '스릴링·원 웨이' },
    artist: 'Aqours',
    year: 2017,
    alias: ['스릴링 원 웨이', '스리원'],
  },
  {
    id: 'A0029',
    name: { jp: '太陽を追いかけろ！', kr: '태양을 쫓아가자!' },
    artist: 'Aqours',
    year: 2017,
    alias: [],
  },
  {
    id: 'A0030',
    name: { jp: 'Guilty Eyes Fever', kr: 'Guilty Eyes Fever' },
    artist: 'Guilty Kiss',
    year: 2017,
    alias: ['길티 아이즈 피버'],
  },
  {
    id: 'A0031',
    name: { jp: 'P.S.の向こう側', kr: 'P.S.의 건너편' },
    artist: 'CYaRon！',
    year: 2017,
    alias: [],
  },
  {
    id: 'A0032',
    name: { jp: 'LONELY TUNING', kr: 'LONELY TUNING' },
    artist: 'AZALEA',
    year: 2017,
    alias: ['론리 튜닝'],
  },
  {
    id: 'A0033',
    name: { jp: 'ジングルベルがとまらない', kr: '징글벨이 멈추지 않아' },
    artist: 'Aqours',
    year: 2016,
    alias: ['징글', '징토마'],
  },
  {
    id: 'A0034',
    name: { jp: '聖なる日の祈り', kr: '성스러운 날의 기도' },
    artist: 'Aqours',
    year: 2016,
    alias: ['세이이노', '세이노'],
  },
  {
    id: 'A0035',
    name: { jp: 'HAPPY PARTY TRAIN', kr: 'HAPPY PARTY TRAIN' },
    artist: 'Aqours',
    year: 2017,
    alias: ['해피 파티 트레인', '해파트', 'HPT'],
  },
  {
    id: 'A0036',
    name: { jp: 'SKY JOURNEY', kr: 'SKY JOURNEY' },
    artist: 'Aqours',
    year: 2017,
    alias: ['스카이 져니', '스카져니'],
  },
  {
    id: 'A0037',
    name: { jp: '少女以上の恋がしたい', kr: '소녀 이상의 사랑이 하고 싶어' },
    artist: 'Aqours',
    year: 2017,
    alias: ['소녀이상', '쇼죠이죠'],
  },
  {
    id: 'A0038',
    name: { jp: '近未来ハッピーエンド', kr: '근미래 해피엔드' },
    artist: 'CYaRon！',
    year: 2017,
    alias: [],
  },
  {
    id: 'A0039',
    name: { jp: '海岸通りで待ってるよ', kr: '해안 도로에서 기다릴게' },
    artist: 'CYaRon！',
    year: 2017,
    alias: ['즈챠챠챠', '즛챠챠챠'],
  },
  {
    id: 'A0040',
    name: { jp: 'GALAXY HidE and SeeK', kr: 'GALAXY HidE and SeeK' },
    artist: 'AZALEA',
    year: 2017,
    alias: ['갤럭시 하이드 앤 시크', '갤하싴', 'GHaS'],
  },
  {
    id: 'A0041',
    name: { jp: 'INNOCENT BIRD', kr: 'INNOCENT BIRD' },
    artist: 'AZALEA',
    year: 2017,
    alias: ['이노센트 버드'],
  },
  {
    id: 'A0042',
    name: { jp: 'コワレヤスキ', kr: '부서지기 쉬운 사랑' },
    artist: 'Guilty Kiss',
    year: 2017,
    alias: ['코와레야스키', 'Fragilove'],
  },
  {
    id: 'A0043',
    name: { jp: 'Shadow gate to love', kr: 'Shadow gate to love' },
    artist: 'Guilty Kiss',
    year: 2017,
    alias: ['섀도게'],
  },
  {
    id: 'A0044',
    name: { jp: 'Landing action Yeah!!', kr: 'Landing action Yeah!!' },
    artist: 'Aqours',
    year: 2017,
    alias: ['랜딩 액션 예!!!', '랜액', 'LaY'],
  },
  {
    id: 'A0045',
    name: { jp: '夏への扉 Never end ver.', kr: '여름으로의 문 Never end ver.' },
    artist: '사쿠라우치 리코, 쿠니키다 하나마루, 오하라 마리',
    year: 2017,
    alias: ['나츠토비', '허리케인 블로섬'],
  },
  {
    id: 'A0046',
    name: { jp: '真夏は誰のモノ？', kr: '한여름은 누구의 것?' },
    artist: '쿠로사와 다이아, 쿠로사와 루비',
    year: 2017,
    alias: ['마나다레', '인페르노 피닉스', '인페르노 삐긱스'],
  },
  {
    id: 'A0047',
    name: { jp: '地元愛♡満タン☆サマーライフ', kr: '고향 사랑♡가득 담은☆서머 라이프' },
    artist: '와타나베 요우, 츠시마 요시코',
    year: 2017,
    alias: ['지모아이', '유니콘 블리자드'],
  },
  {
    id: 'A0048',
    name: { jp: '夏の終わりの雨音が', kr: '여름 끝의 빗소리가' },
    artist: '타카미 치카, 마츠우라 카난',
    year: 2017,
    alias: ['나츠아메', '트와일라잇 타이거', '황혼 호랑이'],
  },
  {
    id: 'A0049',
    name: { jp: '未来の僕らは知ってるよ', kr: '미래의 우리는 알고 있어' },
    artist: 'Aqours',
    year: 2017,
    alias: ['미라보쿠'],
  },
  {
    id: 'A0050',
    name: { jp: '君の瞳を巡る冒険', kr: '너의 눈동자를 둘러싼 모험' },
    artist: 'Aqours',
    year: 2017,
    alias: ['키미보켄'],
  },
  {
    id: 'A0051',
    name: { jp: '勇気はどこに？君の胸に！', kr: '용기는 어디에? 너의 가슴에!' },
    artist: 'Aqours',
    year: 2017,
    alias: ['유우키미'],
  },
  {
    id: 'A0052',
    name: { jp: '“MY LIST” to you!', kr: '“MY LIST” to you!' },
    artist: 'Aqours',
    year: 2017,
    alias: ['"MY LIST" to you!', '마이 리스트 투 유', '바밤바'],
  },
  {
    id: 'A0053',
    name: { jp: 'MY舞☆TONIGHT', kr: 'MY무희☆TONIGHT' },
    artist: 'Aqours',
    year: 2017,
    alias: ['마이마이'],
  },
  {
    id: 'A0054',
    name: { jp: 'MIRACLE WAVE', kr: 'MIRACLE WAVE' },
    artist: 'Aqours',
    year: 2017,
    alias: ['미라웨이', '미라웨브'],
  },
  {
    id: 'A0055',
    name: { jp: 'Awaken the power', kr: 'Awaken the power' },
    artist: 'Saint Aqours Snow',
    year: 2017,
    alias: ['어윀파'],
  },
  {
    id: 'A0056',
    name: { jp: 'CRASH MIND', kr: 'CRASH MIND' },
    artist: 'Saint Snow',
    year: 2017,
    alias: ['크래시 마인드'],
  },
  {
    id: 'A0057',
    name: { jp: 'DROPOUT!?', kr: 'DROPOUT!?' },
    artist: 'Saint Snow',
    year: 2017,
    alias: ['드롭아웃'],
  },
  {
    id: 'A0058',
    name: { jp: 'WATER BLUE NEW WORLD', kr: 'WATER BLUE NEW WORLD' },
    artist: 'Aqours',
    year: 2018,
    alias: ['워터 블루 뉴 월드', 'WBNW'],
  },
  {
    id: 'A0059',
    name: { jp: 'WONDERFUL STORIES', kr: 'WONDERFUL STORIES' },
    artist: 'Aqours',
    year: 2018,
    alias: ['원더풀 스토리', 'WS'],
  },
  {
    id: 'A0060',
    name: { jp: 'One More Sunshine Story', kr: 'One More Sunshine Story' },
    artist: '타카미 치카',
    year: 2017,
    alias: [],
  },
  {
    id: 'A0061',
    name: { jp: 'おやすみなさん！', kr: '안녕히 주무세여러분!' },
    artist: '쿠니키다 하나마루',
    year: 2018,
    alias: ['오야스미나상!'],
  },
  {
    id: 'A0062',
    name: { jp: 'in this unstable world', kr: 'in this unstable world' },
    artist: '츠시마 요시코',
    year: 2018,
    alias: [],
  },
  {
    id: 'A0063',
    name: { jp: 'Pianoforte Monologue', kr: 'Pianoforte Monologue' },
    artist: '사쿠라우치 리코',
    year: 2018,
    alias: ['피아노포르테 모노로그'],
  },
  {
    id: 'A0064',
    name: { jp: 'Beginner\'s Sailing', kr: 'Beginner\'s Sailing' },
    artist: '와타나베 요우',
    year: 2018,
    alias: ['비기너 세일링'],
  },
  {
    id: 'A0065',
    name: { jp: 'RED GEM WINK', kr: 'RED GEM WINK' },
    artist: '쿠로사와 루비',
    year: 2018,
    alias: ['레드 젬 윙크'],
  },
  {
    id: 'A0066',
    name: { jp: 'WHITE FIRST LOVE', kr: 'WHITE FIRST LOVE' },
    artist: '쿠로사와 다이아',
    year: 2018,
    alias: ['엘사'],
  },
  {
    id: 'A0067',
    name: { jp: 'New winding road', kr: 'New winding road' },
    artist: '오하라 마리',
    year: 2018,
    alias: [],
  },
  {
    id: 'A0068',
    name: { jp: 'さかなかなんだか？', kr: '물고기 카난일까?' },
    artist: '마츠우라 카난',
    year: 2018,
    alias: ['사카나카난다카?'],
  },
  {
    id: 'A0069',
    name: { jp: 'キセキヒカル', kr: '기적이, 빛나다' },
    artist: 'Aqours',
    year: 2018,
    alias: ['키세키 히카루', '키세히카'],
  },
  {
    id: 'A0070',
    name: { jp: 'Guilty!? Farewell party', kr: 'Guilty!? Farewell party' },
    artist: 'Guilty Kiss',
    year: 2018,
    alias: [],
  },
  {
    id: 'A0071',
    name: { jp: 'サクラバイバイ', kr: '벚꽃 바이바이' },
    artist: 'CYaRon！',
    year: 2018,
    alias: ['사쿠라 바이바이'],
  },
  {
    id: 'A0072',
    name: { jp: '卒業ですね', kr: '졸업이네요' },
    artist: 'AZALEA',
    year: 2018,
    alias: [],
  },
];

// LOVELIVE_SUNSHINE_SONGS.forEach((song, idx) => {
//   if (LOVELIVE_SUNSHINE_SONGS.slice(idx + 1).findIndex((e) => e.id === song.id) > -1) {
//     throw Error(`Duplicate ID: ${song.id}`);
//   }
// });
