import { SongEntry } from './types';

// Aliases from: https://xn--hckp3ac2l023wu2ve.com/live-music-ryakushou-matome.html
export const LOVELIVE_SUNSHINE_SONGS: SongEntry[] = [
  {
    id: 'A0001',
    name: { jp: '君のこころは輝いてるかい？', kr: '너의 마음은 빛나고 있니?' },
    artist: 'Aqours',
    year: 2015,
    alias: ['키미노 코코로와 카가야이테루카이?', '키미코코'],
  },
  {
    id: 'A0002',
    name: { jp: 'Step! ZERO to ONE', kr: 'Step! ZERO to ONE' },
    artist: 'Aqours',
    year: 2015,
    alias: ['스텝 제로 투 원', '스텝! 제로 투 원', '01', '제로원'],
  },
  {
    id: 'A0003',
    name: { jp: 'Aqours☆HEROES', kr: 'Aqours☆HEROES' },
    artist: 'Aqours',
    year: 2015,
    alias: ['아쿠아 히어로', '히로'],
  },
  {
    id: 'A0004',
    name: { jp: '恋になりたいAQUARIUM', kr: '사랑이 되고 싶은 AQUARIUM' },
    artist: 'Aqours',
    year: 2016,
    alias: ['코이니 나리타이 아쿠아리움', '코이아쿠'],
  },
  {
    id: 'A0005',
    name: { jp: '待ってて愛のうた', kr: '기다려줘 사랑의 노래' },
    artist: 'Aqours',
    year: 2016,
    alias: ['맛떼떼 아이노 우타', '맛떼아이', '맛테아이', '아이우타'],
  },
  {
    id: 'A0006',
    name: { jp: '届かない星だとしても', kr: '닿을 수 없는 별이라 해도' },
    artist: 'Aqours',
    year: 2016,
    alias: ['토도카나이 호시다토 시테모', '토도호시'],
  },
  {
    id: 'A0007',
    name: { jp: '元気全開DAY! DAY! DAY!', kr: '활기전개 DAY! DAY! DAY!' },
    artist: 'CYaRon！',
    year: 2016,
    alias: ['원기전개 DAY! DAY! DAY!', '겡키 젠카이 데이데이데이', 'DDD'],
  },
  {
    id: 'A0008',
    name: { jp: '夜空はなんでも知ってるの？', kr: '밤하늘은 뭐든지 알고 있는 거야?' },
    artist: 'CYaRon！',
    year: 2016,
    alias: ['요조라와 난데모 싯떼루노?', '요조라', '요조싯떼'],
  },
  {
    id: 'A0009',
    name: { jp: 'トリコリコPLEASE!!', kr: '토리코리코PLEASE!!' },
    artist: 'AZALEA',
    year: 2016,
    alias: ['토리코리코 플리즈!!'],
  },
  {
    id: 'A0010',
    name: { jp: 'ときめき分類学', kr: '두근거림 분류학' },
    artist: 'AZALEA',
    year: 2016,
    alias: ['토키메키 분류학', '도키메키 분류학'],
  },
  {
    id: 'A0011',
    name: { jp: 'Strawberry Trapper', kr: 'Strawberry Trapper' },
    artist: 'Guilty Kiss',
    year: 2016,
    alias: ['스트로베리 트래퍼', '스트토라', '스토토라', '딸기 함정꾼'],
  },
  {
    id: 'A0012',
    name: { jp: 'Guilty Night, Guilty Kiss!', kr: 'Guilty Night, Guilty Kiss!' },
    artist: 'Guilty Kiss',
    year: 2016,
    alias: ['길티 나잇, 길티 키스!', '길티 나잇 길티 키스', '길낫길키', '기루나이', 'GNGK'],
  },
  {
    id: 'A0013',
    name: { jp: '青空Jumping Heart', kr: '푸른 하늘 Jumping Heart' },
    artist: 'Aqours',
    year: 2016,
    alias: ['아오조라 점핑하트', '아오잠', '아오쟘'],
  },
  {
    id: 'A0014',
    name: { jp: 'ハミングフレンド', kr: '허밍 프렌드' },
    artist: 'Aqours',
    year: 2016,
    alias: [],
  },
  {
    id: 'A0015',
    name: { jp: 'ユメ語るよりユメ歌おう', kr: '꿈을 말하기보다 꿈을 노래하자' },
    artist: 'Aqours',
    year: 2016,
    alias: ['유메유메'],
  },
  {
    id: 'A0016',
    name: { jp: 'サンシャインぴっかぴか音頭', kr: '선샤인 반짝반짝 선창' },
    artist: 'Aqours',
    year: 2016,
    alias: ['선샤인 피카피카 온도', '선샤인 삐까삐까 온도'],
  },
  {
    id: 'A0017',
    name: { jp: '決めたよHand in Hand', kr: '결정했어 Hand in Hand' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우',
    year: 2016,
    alias: ['키메타요 핸드 인 핸드', '핸인핸', '키메한'],
  },
  {
    id: 'A0018',
    name: { jp: 'ダイスキだったらダイジョウブ！', kr: '정말로 좋아한다면 괜찮을 거야!' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우',
    year: 2016,
    alias: ['다이스키닷타라 다이죠부', '다이다이', '다다다'],
  },
  {
    id: 'A0019',
    name: { jp: '夢で夜空を照らしたい', kr: '꿈으로 밤하늘을 비추고 싶어' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우, 츠시마 요시코, 쿠니키다 하나마루, 쿠로사와 루비',
    year: 2016,
    alias: ['유메요조', '유메테라'],
  },
  {
    id: 'A0020',
    name: { jp: '未熟DREAMER', kr: '미숙 DREAMER' },
    artist: 'Aqours',
    year: 2016,
    alias: ['미숙 드리머'],
  },
  {
    id: 'A0021',
    name: { jp: '想いよひとつになれ', kr: '마음이여 하나가 되어라' },
    artist: '타카미 치카, 마츠우라 카난, 쿠로사와 다이아, 와타나베 요우, 츠시마 요시코, 쿠니키다 하나마루, 오하라 마리, 쿠로사와 루비',
    year: 2016,
    alias: ['오모이요 히토츠니 나레', '오모히토'],
  },
  {
    id: 'A0022',
    name: { jp: 'MIRAI TICKET', kr: 'MIRAI TICKET' },
    artist: 'Aqours',
    year: 2016,
    alias: ['미래 티켓', '미라치케'],
  },
  {
    id: 'A0138',
    name: { jp: 'SELF CONTROL!!', kr: 'SELF CONTROL!!' },
    artist: 'Saint Snow',
    year: 2016,
    alias: ['셀프 컨트롤!!', '셀컨'],
  },
  {
    id: 'A0023',
    name: { jp: 'Pops heartで踊るんだもん！', kr: 'Pops heart로 춤추는걸!' },
    artist: 'Aqours',
    year: 2016,
    alias: ['팝스하트'],
  },
  {
    id: 'A0024',
    name: { jp: '空も心も晴れるから', kr: '하늘도 마음도 맑을 테니까' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우',
    year: 2016,
    alias: ['소라하레'],
  },
  {
    id: 'A0025',
    name: { jp: 'Waku-Waku-Week!', kr: 'Waku-Waku-Week!' },
    artist: '츠시마 요시코, 쿠니키다 하나마루, 쿠로사와 루비',
    year: 2016,
    alias: ['와쿠와쿠위크', 'WWW'],
  },
  {
    id: 'A0026',
    name: { jp: 'Daydream Warrior', kr: 'Daydream Warrior' },
    artist: 'Aqours',
    year: 2016,
    alias: ['데이드림 워리어', '데이워리'],
  },
  {
    id: 'A0027',
    name: { jp: 'G線上のシンデレラ', kr: 'G선상의 신데렐라' },
    artist: '마츠우라 카난, 쿠로사와 다이아, 오하라 마리',
    year: 2017,
    alias: ['지선상의 신데렐라', 'G데렐라'],
  },
  {
    id: 'A0028',
    name: { jp: 'スリリング・ワンウェイ', kr: '스릴링·원 웨이' },
    artist: 'Aqours',
    year: 2017,
    alias: ['스릴링 원 웨이', '스리원'],
  },
  {
    id: 'A0029',
    name: { jp: '太陽を追いかけろ！', kr: '태양을 쫓아가자!' },
    artist: 'Aqours',
    year: 2017,
    alias: [],
  },
  {
    id: 'A0030',
    name: { jp: 'Guilty Eyes Fever', kr: 'Guilty Eyes Fever' },
    artist: 'Guilty Kiss',
    year: 2017,
    alias: ['길티 아이즈 피버'],
  },
  {
    id: 'A0031',
    name: { jp: 'P.S.の向こう側', kr: 'P.S.의 건너편' },
    artist: 'CYaRon！',
    year: 2017,
    alias: [],
  },
  {
    id: 'A0032',
    name: { jp: 'LONELY TUNING', kr: 'LONELY TUNING' },
    artist: 'AZALEA',
    year: 2017,
    alias: ['론리 튜닝'],
  },
  {
    id: 'A0033',
    name: { jp: 'ジングルベルがとまらない', kr: '징글벨이 멈추지 않아' },
    artist: 'Aqours',
    year: 2016,
    alias: ['징글', '징토마'],
  },
  {
    id: 'A0034',
    name: { jp: '聖なる日の祈り', kr: '성스러운 날의 기도' },
    artist: 'Aqours',
    year: 2016,
    alias: ['세이이노', '세이노'],
  },
  {
    id: 'A0035',
    name: { jp: 'HAPPY PARTY TRAIN', kr: 'HAPPY PARTY TRAIN' },
    artist: 'Aqours',
    year: 2017,
    alias: ['해피 파티 트레인', '해파트', 'HPT'],
  },
  {
    id: 'A0036',
    name: { jp: 'SKY JOURNEY', kr: 'SKY JOURNEY' },
    artist: 'Aqours',
    year: 2017,
    alias: ['스카이 져니', '스카져니'],
  },
  {
    id: 'A0037',
    name: { jp: '少女以上の恋がしたい', kr: '소녀 이상의 사랑이 하고 싶어' },
    artist: 'Aqours',
    year: 2017,
    alias: ['소녀이상', '쇼죠이죠'],
  },
  {
    id: 'A0038',
    name: { jp: '近未来ハッピーエンド', kr: '근미래 해피엔드' },
    artist: 'CYaRon！',
    year: 2017,
    alias: [],
  },
  {
    id: 'A0039',
    name: { jp: '海岸通りで待ってるよ', kr: '해안 도로에서 기다릴게' },
    artist: 'CYaRon！',
    year: 2017,
    alias: ['즈챠챠챠', '즛챠챠챠'],
  },
  {
    id: 'A0040',
    name: { jp: 'GALAXY HidE and SeeK', kr: 'GALAXY HidE and SeeK' },
    artist: 'AZALEA',
    year: 2017,
    alias: ['갤럭시 하이드 앤 시크', '갤하싴', 'GHaS'],
  },
  {
    id: 'A0041',
    name: { jp: 'INNOCENT BIRD', kr: 'INNOCENT BIRD' },
    artist: 'AZALEA',
    year: 2017,
    alias: ['이노센트 버드'],
  },
  {
    id: 'A0042',
    name: { jp: 'コワレヤスキ', kr: '부서지기 쉬운 사랑' },
    artist: 'Guilty Kiss',
    year: 2017,
    alias: ['코와레야스키', 'Fragilove'],
  },
  {
    id: 'A0043',
    name: { jp: 'Shadow gate to love', kr: 'Shadow gate to love' },
    artist: 'Guilty Kiss',
    year: 2017,
    alias: ['섀도게'],
  },
  {
    id: 'A0044',
    name: { jp: 'Landing action Yeah!!', kr: 'Landing action Yeah!!' },
    artist: 'Aqours',
    year: 2017,
    alias: ['랜딩 액션 예!!!', '랜액', 'LaY'],
  },
  {
    id: 'A0045',
    name: { jp: '夏への扉 Never end ver.', kr: '여름으로의 문 Never end ver.' },
    artist: '사쿠라우치 리코, 쿠니키다 하나마루, 오하라 마리',
    year: 2017,
    alias: ['나츠토비', '허리케인 블로섬'],
  },
  {
    id: 'A0046',
    name: { jp: '真夏は誰のモノ？', kr: '한여름은 누구의 것?' },
    artist: '쿠로사와 다이아, 쿠로사와 루비',
    year: 2017,
    alias: ['마나다레', '인페르노 피닉스', '인페르노 삐긱스'],
  },
  {
    id: 'A0047',
    name: { jp: '地元愛♡満タン☆サマーライフ', kr: '고향 사랑♡가득 담은☆서머 라이프' },
    artist: '와타나베 요우, 츠시마 요시코',
    year: 2017,
    alias: ['지모아이', '유니콘 블리자드', 'ㄴㅇㄱ'],
  },
  {
    id: 'A0048',
    name: { jp: '夏の終わりの雨音が', kr: '여름 끝의 빗소리가' },
    artist: '타카미 치카, 마츠우라 카난',
    year: 2017,
    alias: ['나츠아메', '트와일라잇 타이거', '황혼 호랑이'],
  },
  {
    id: 'A0049',
    name: { jp: '未来の僕らは知ってるよ', kr: '미래의 우리는 알고 있어' },
    artist: 'Aqours',
    year: 2017,
    alias: ['미라보쿠'],
  },
  {
    id: 'A0050',
    name: { jp: '君の瞳を巡る冒険', kr: '너의 눈동자를 둘러싼 모험' },
    artist: 'Aqours',
    year: 2017,
    alias: ['키미보켄'],
  },
  {
    id: 'A0051',
    name: { jp: '勇気はどこに？君の胸に！', kr: '용기는 어디에? 너의 가슴에!' },
    artist: 'Aqours',
    year: 2017,
    alias: ['유우키미'],
  },
  {
    id: 'A0052',
    name: { jp: '“MY LIST” to you!', kr: '“MY LIST” to you!' },
    artist: 'Aqours',
    year: 2017,
    alias: ['"MY LIST" to you!', '마이 리스트 투 유', '바밤바'],
  },
  {
    id: 'A0053',
    name: { jp: 'MY舞☆TONIGHT', kr: 'MY무희☆TONIGHT' },
    artist: 'Aqours',
    year: 2017,
    alias: ['마이마이'],
  },
  {
    id: 'A0054',
    name: { jp: 'MIRACLE WAVE', kr: 'MIRACLE WAVE' },
    artist: 'Aqours',
    year: 2017,
    alias: ['미라웨이', '미라웨브'],
  },
  {
    id: 'A0055',
    name: { jp: 'Awaken the power', kr: 'Awaken the power' },
    artist: 'Saint Aqours Snow',
    year: 2017,
    alias: ['어윀파', 'ATP'],
  },
  {
    id: 'A0056',
    name: { jp: 'CRASH MIND', kr: 'CRASH MIND' },
    artist: 'Saint Snow',
    year: 2017,
    alias: ['크래시 마인드'],
  },
  {
    id: 'A0057',
    name: { jp: 'DROPOUT!?', kr: 'DROPOUT!?' },
    artist: 'Saint Snow',
    year: 2017,
    alias: ['드롭아웃'],
  },
  {
    id: 'A0058',
    name: { jp: 'WATER BLUE NEW WORLD', kr: 'WATER BLUE NEW WORLD' },
    artist: 'Aqours',
    year: 2018,
    alias: ['워터 블루 뉴 월드', 'WBNW'],
  },
  {
    id: 'A0059',
    name: { jp: 'WONDERFUL STORIES', kr: 'WONDERFUL STORIES' },
    artist: 'Aqours',
    year: 2018,
    alias: ['원더풀 스토리', 'WS'],
  },
  {
    id: 'A0060',
    name: { jp: 'One More Sunshine Story', kr: 'One More Sunshine Story' },
    artist: '타카미 치카',
    year: 2017,
    alias: [],
  },
  {
    id: 'A0061',
    name: { jp: 'おやすみなさん！', kr: '안녕히 주무세여러분!' },
    artist: '쿠니키다 하나마루',
    year: 2018,
    alias: ['오야스미나상!'],
  },
  {
    id: 'A0062',
    name: { jp: 'in this unstable world', kr: 'in this unstable world' },
    artist: '츠시마 요시코',
    year: 2018,
    alias: [],
  },
  {
    id: 'A0063',
    name: { jp: 'Pianoforte Monologue', kr: 'Pianoforte Monologue' },
    artist: '사쿠라우치 리코',
    year: 2018,
    alias: ['피아노포르테 모노로그'],
  },
  {
    id: 'A0064',
    name: { jp: 'Beginner\'s Sailing', kr: 'Beginner\'s Sailing' },
    artist: '와타나베 요우',
    year: 2018,
    alias: ['비기너 세일링'],
  },
  {
    id: 'A0065',
    name: { jp: 'RED GEM WINK', kr: 'RED GEM WINK' },
    artist: '쿠로사와 루비',
    year: 2018,
    alias: ['레드 젬 윙크'],
  },
  {
    id: 'A0066',
    name: { jp: 'WHITE FIRST LOVE', kr: 'WHITE FIRST LOVE' },
    artist: '쿠로사와 다이아',
    year: 2018,
    alias: ['엘사'],
  },
  {
    id: 'A0067',
    name: { jp: 'New winding road', kr: 'New winding road' },
    artist: '오하라 마리',
    year: 2018,
    alias: [],
  },
  {
    id: 'A0068',
    name: { jp: 'さかなかなんだか？', kr: '물고기 카난일까?' },
    artist: '마츠우라 카난',
    year: 2018,
    alias: ['사카나카난다카?'],
  },
  {
    id: 'A0069',
    name: { jp: 'キセキヒカル', kr: '기적이, 빛나다' },
    artist: 'Aqours',
    year: 2018,
    alias: ['키세키 히카루', '키세히카'],
  },
  {
    id: 'A0070',
    name: { jp: 'Guilty!? Farewell party', kr: 'Guilty!? Farewell party' },
    artist: 'Guilty Kiss',
    year: 2018,
    alias: [],
  },
  {
    id: 'A0071',
    name: { jp: 'サクラバイバイ', kr: '벚꽃 바이바이' },
    artist: 'CYaRon！',
    year: 2018,
    alias: ['사쿠라 바이바이'],
  },
  {
    id: 'A0072',
    name: { jp: '卒業ですね', kr: '졸업이네요' },
    artist: 'AZALEA',
    year: 2018,
    alias: [],
  },
  {
    id: 'A0073',
    name: { jp: 'ホップ・ステップ・ワーイ！', kr: 'Hop・Step・와이!' },
    artist: 'Aqours',
    year: 2018,
    alias: ['홉 스텝 와이!', '홉스와'],
  },
  {
    id: 'A0074',
    name: { jp: 'Thank you, FRIENDS!!', kr: 'Thank you, FRIENDS!!' },
    artist: 'Aqours',
    year: 2018,
    alias: ['땡프', '워워워워'],
  },
  {
    id: 'A0075',
    name: { jp: 'No.10', kr: 'No.10' },
    artist: 'Aqours',
    year: 2018,
    alias: ['넘텐', '넘버텐'],
  },
  {
    id: 'A0076',
    name: { jp: '僕らの走ってきた道は・・・', kr: '우리가 달려온 길은…' },
    artist: 'Aqours',
    year: 2019,
    alias: ['보쿠미치'],
  },
  {
    id: 'A0077',
    name: { jp: 'Next SPARKLING!!', kr: 'Next SPARKLING!!' },
    artist: 'Aqours',
    year: 2019,
    alias: ['넥스트 스파클링!!', '넥스파'],
  },
  {
    id: 'A0078',
    name: { jp: '逃走迷走メビウスループ', kr: '도주 미주 뫼비우스 루프' },
    artist: '마츠우라 카난, 쿠로사와 다이아, 오하라 마리',
    year: 2019,
    alias: ['도망 황망 뫼비우스의 띠'],
  },
  {
    id: 'A0079',
    name: { jp: 'Hop? Stop? Nonstop!', kr: 'Hop? Stop? Nonstop!' },
    artist: 'Aqours',
    year: 2019,
    alias: ['홉 스탑 논스탑', '홉스논'],
  },
  {
    id: 'A0080',
    name: { jp: 'Believe again', kr: 'Believe again' },
    artist: 'Saint Snow',
    year: 2019,
    alias: ['빌립 어겐', '빌리브 어게인'],
  },
  {
    id: 'A0081',
    name: { jp: 'Brightest Melody', kr: 'Brightest Melody' },
    artist: 'Aqours',
    year: 2019,
    alias: ['브라메로', '브라멜로'],
  },
  {
    id: 'A0082',
    name: { jp: 'Over The Next Rainbow', kr: 'Over The Next Rainbow' },
    artist: 'Saint Aqours Snow',
    year: 2019,
    alias: ['OTNR'],
  },
  {
    id: 'A0083',
    name: { jp: 'i-n-g, I TRY!!', kr: 'i-n-g, I TRY!!' },
    artist: 'Aqours',
    year: 2019,
    alias: ['잉트라이', 'ing I TRY!!'],
  },
  {
    id: 'A0084',
    name: { jp: 'ハジマリロード', kr: '하지마리로드' },
    artist: '츠시마 요시코, 쿠니키다 하나마루, 쿠로사와 루비',
    year: 2018,
    alias: ['시작의 길'],
  },
  {
    id: 'A0085',
    name: { jp: 'Marine Border Parasol', kr: 'Marine Border Parasol' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우',
    year: 2018,
    alias: ['마린 보더 파라솔'],
  },
  {
    id: 'A0086',
    name: { jp: '予測不可能Driving!', kr: '예측불가능 Driving!' },
    artist: '마츠우라 카난, 쿠로사와 다이아, 오하라 마리',
    year: 2018,
    alias: [],
  },
  {
    id: 'A0087',
    name: { jp: 'Jump up HIGH!!', kr: 'Jump up HIGH!!' },
    artist: 'Aqours',
    year: 2019,
    alias: ['점프 업 하이!!', '짬빱'],
  },
  {
    id: 'A0088',
    name: { jp: '冒険Type A, B, C‼', kr: '모험 Type A, B, C!!' },
    artist: 'Aqours',
    year: 2019,
    alias: [],
  },
  {
    id: 'A0089',
    name: { jp: '未体験HORIZON', kr: '미체험 HORIZON' },
    artist: 'Aqours',
    year: 2019,
    alias: ['미호라'],
  },
  {
    id: 'A0090',
    name: { jp: 'Deep Resonance', kr: 'Deep Resonance' },
    artist: 'Aqours',
    year: 2019,
    alias: ['딥 레조넌스', '딥레조'],
  },
  {
    id: 'A0091',
    name: { jp: 'Dance with Minotaurus', kr: 'Dance with Minotaurus' },
    artist: 'Aqours',
    year: 2019,
    alias: ['댄스 위드 미노타우르스', '흑우춤'],
  },
  {
    id: 'A0092',
    name: { jp: 'KOKORO Magic “A to Z”', kr: 'KOKORO Magic “A to Z”' },
    artist: 'Aqours',
    year: 2019,
    alias: ['KOKORO Magic A to Z', '코코로 매직 A to Z', '코코마지'],
  },
  {
    id: 'A0093',
    name: { jp: 'Wake up, Challenger!!', kr: 'Wake up, Challenger!!' },
    artist: 'Aqours',
    year: 2019,
    alias: ['웨이크 업 챌린저!!', '웨업챌', 'WUC'],
  },
  {
    id: 'A0094',
    name: { jp: 'New Romantic Sailors', kr: 'New Romantic Sailors' },
    artist: 'Guilty Kiss',
    year: 2019,
    alias: ['뉴 로맨틱 세일러', '뉴로세', 'NRS'],
  },
  {
    id: 'A0095',
    name: { jp: 'Love Pulsar', kr: 'Love Pulsar' },
    artist: 'Guilty Kiss',
    year: 2019,
    alias: ['러브 펄서', 'LP'],
  },
  {
    id: 'A0096',
    name: { jp: 'Phantom Rocket Adventure', kr: 'Phantom Rocket Adventure' },
    artist: 'Guilty Kiss',
    year: 2019,
    alias: ['팬텀 로켓 어드벤쳐', 'PRA'],
  },
  {
    id: 'A0097',
    name: { jp: 'Braveheart Coaster', kr: 'Braveheart Coaster' },
    artist: 'CYaRon！',
    year: 2019,
    alias: ['브레이브하트 코스터', '브하코', 'BHC'],
  },
  {
    id: 'A0098',
    name: { jp: 'CHANGELESS', kr: 'CHANGELESS' },
    artist: 'CYaRon！',
    year: 2019,
    alias: ['체인지리스', '체인지레스'],
  },
  {
    id: 'A0099',
    name: { jp: 'コドク・テレポート', kr: '고독·텔레포트' },
    artist: 'CYaRon！',
    year: 2019,
    alias: ['고독 텔레포트'],
  },
  {
    id: 'A0100',
    name: { jp: 'Amazing Travel DNA', kr: 'Amazing Travel DNA' },
    artist: 'AZALEA',
    year: 2019,
    alias: ['어메이징 트래블 디엔에이', 'ATD'],
  },
  {
    id: 'A0101',
    name: { jp: '空中恋愛論', kr: '공중연애론' },
    artist: 'AZALEA',
    year: 2019,
    alias: [],
  },
  {
    id: 'A0102',
    name: { jp: 'メイズセカイ', kr: '미궁세계' },
    artist: 'AZALEA',
    year: 2019,
    alias: ['메이즈세카이'],
  },
  {
    id: 'A0103',
    name: { jp: 'シャゼリア☆キッス☆ダダンダーン', kr: '샤젤리아☆키스☆다당당' },
    artist: 'CYaZALEA☆Kiss',
    year: 2020,
    alias: ['샤젤리아 키스', '샤제리아 키스'],
  },
  {
    id: 'A0104',
    name: { jp: 'Fantastic Departure!', kr: 'Fantastic Departure!' },
    artist: 'Aqours',
    year: 2020,
    alias: ['판타스틱 디파쳐', '판디파', 'FD', '레츠 라이동'],
  },
  {
    id: 'A0105',
    name: { jp: 'Aqours Pirates Desire', kr: 'Aqours Pirates Desire' },
    artist: 'Aqours',
    year: 2020,
    alias: ['APD', '해적'],
  },
  {
    id: 'A0106',
    name: { jp: 'Never giving up!', kr: 'Never giving up!' },
    artist: '타카미 치카',
    year: 2020,
    alias: [],
  },
  {
    id: 'A0107',
    name: { jp: 'Dazzling White Town', kr: 'Dazzling White Town' },
    artist: 'Saint Snow',
    year: 2020,
    alias: ['대즐링 화이트 타운', 'DWT'],
  },
  {
    id: 'A0108',
    name: { jp: 'Lonely Snow Planet', kr: 'Lonely Snow Planet' },
    artist: 'Saint Snow',
    year: 2020,
    alias: ['LSP'],
  },
  {
    id: 'A0109',
    name: { jp: 'After The Rain', kr: 'After The Rain' },
    artist: 'Saint Snow',
    year: 2020,
    alias: ['ATR'],
  },
  {
    id: 'A0110',
    name: { jp: 'JIMO-AI Dash!', kr: 'JIMO-AI Dash!' },
    artist: 'Aqours',
    year: 2020,
    alias: ['지모아이 대시!'],
  },
  {
    id: 'A0111',
    name: { jp: 'PURE PHRASE', kr: 'PURE PHRASE' },
    artist: '사쿠라우치 리코',
    year: 2020,
    alias: ['퓨프'],
  },
  {
    id: 'A0112',
    name: { jp: 'コットンキャンディえいえいおー！', kr: '코튼 캔디 에이 에이 오!' },
    artist: '쿠로사와 루비',
    year: 2020,
    alias: ['솜사탕'],
  },
  {
    id: 'A0113',
    name: { jp: 'Future flight', kr: 'Future flight' },
    artist: 'Aqours',
    year: 2020,
    alias: ['퓨쳐 플라이트', '퓨플'],
  },
  {
    id: 'A0114',
    name: { jp: '空も心も晴れるから (Aqours)', kr: '하늘도 마음도 맑을 테니까 (Aqours)' },
    artist: 'Aqours',
    year: 2020,
    alias: ['소라하레'],
    excludable: true,
  },
  {
    id: 'A0115',
    name: { jp: 'キモチもユメも一緒だね！', kr: '마음도 꿈도 함께네!' },
    artist: '쿠니키다 하나마루, 쿠로사와 루비',
    year: 2020,
    alias: [],
  },
  {
    id: 'A0116',
    name: { jp: '涙が雪になる前に', kr: '눈물이 눈이 되기 전에' },
    artist: '마츠우라 카난, 오하라 마리',
    year: 2020,
    alias: [],
  },
  {
    id: 'A0117',
    name: { jp: 'Misty Frosty Love', kr: 'Misty Frosty Love' },
    artist: '사쿠라우치 리코, 와타나베 요우',
    year: 2020,
    alias: ['미스티 프로스티 러브', 'MFL'],
  },
  {
    id: 'A0118',
    name: { jp: 'Party! Party! PaPaPaParty!', kr: 'Party! Party! PaPaPaParty!' },
    artist: '타카미 치카, 쿠로사와 다이아, 츠시마 요시코',
    year: 2020,
    alias: ['파티 파티 파파파파티', '구린파'],
  },
  {
    id: 'A0119',
    name: { jp: 'Perfect SEKAI', kr: 'Perfect SEKAI' },
    artist: '쿠로사와 다이아',
    year: 2021,
    alias: ['퍼펙트 세카이'],
  },
  {
    id: 'A0120',
    name: { jp: 'もっとね！', kr: '조금 더!' },
    artist: '마츠우라 카난',
    year: 2021,
    alias: ['못또네', '못토네'],
  },
  {
    id: 'A0121',
    name: { jp: 'あこがれランララン', kr: '동경 란라란' },
    artist: '쿠니키다 하나마루',
    year: 2021,
    alias: ['아코가레 란라란'],
  },
  {
    id: 'A0122',
    name: { jp: 'smile smile ship Start!', kr: 'smile smile ship Start!' },
    artist: 'Aqours',
    year: 2021,
    alias: ['스마일 스마일 쉽 스타트!', 'SSSS', '4S'],
  },
  {
    id: 'A0123',
    name: { jp: '心の羽よ君へ飛んでけ！', kr: '마음의 날개여 너에게 날아가라!' },
    artist: 'Aqours',
    year: 2021,
    alias: ['코코하네'],
  },
  {
    id: 'A0124',
    name: { jp: '突然GIRL', kr: '돌연GIRL' },
    artist: '와타나베 요우',
    year: 2021,
    alias: ['갑분걸', '돌연걸'],
  },
  {
    id: 'A0125',
    name: { jp: 'ある日…永遠みたいに！', kr: '어느 날… 영원처럼!' },
    artist: 'CYaRon！',
    year: 2021,
    alias: ['어느 날... 영원처럼!', '어느 날 영원처럼!', '아루히 에이엔 미타이니!'],
  },
  {
    id: 'A0126',
    name: { jp: 'Whistle of Revolution', kr: 'Whistle of Revolution' },
    artist: 'CYaRon！',
    year: 2021,
    alias: [],
  },
  {
    id: 'A0127',
    name: { jp: 'ドラゴンライダーズ', kr: '드래곤 라이더즈' },
    artist: 'CYaRon！',
    year: 2021,
    alias: [],
  },
  {
    id: 'A0128',
    name: { jp: 'Shiny Racers', kr: 'Shiny Racers' },
    artist: '오하라 마리',
    year: 2021,
    alias: ['샤이니 레이서'],
  },
  {
    id: 'A0129',
    name: { jp: 'We‘ll get the next dream!!!', kr: 'We‘ll get the next dream!!!' },
    artist: 'AZALEA',
    year: 2021,
    alias: ['We\'ll get the next dream!!!'],
  },
  {
    id: 'A0130',
    name: { jp: 'PHOENIX DANCE', kr: 'PHOENIX DANCE' },
    artist: 'AZALEA',
    year: 2021,
    alias: ['피닉스 댄스'],
  },
  {
    id: 'A0131',
    name: { jp: 'メタモルフィズム', kr: '메타모르피즘' },
    artist: 'AZALEA',
    year: 2021,
    alias: ['메타몰피즘', '변성 작용'],
  },
  {
    id: 'A0132',
    name: { jp: 'DREAMY COLOR', kr: 'DREAMY COLOR' },
    artist: 'Aqours',
    year: 2021,
    alias: ['드리미 컬러', 'DC', '디씨'],
  },
  {
    id: 'A0133',
    name: { jp: 'タテホコツバサ', kr: '모순의 날개' },
    artist: '츠시마 요시코',
    year: 2021,
    alias: ['타테호코 츠바사'],
  },
  {
    id: 'A0134',
    name: { jp: 'Shooting Star Warrior', kr: 'Shooting Star Warrior' },
    artist: 'Guilty Kiss',
    year: 2021,
    alias: ['슈팅 스타 워리어', 'SSW'],
  },
  {
    id: 'A0135',
    name: { jp: 'Deep Sea Cocoon', kr: 'Deep Sea Cocoon' },
    artist: 'Guilty Kiss',
    year: 2021,
    alias: ['딥 시 코쿤', 'DSC'],
  },
  {
    id: 'A0136',
    name: { jp: 'Nameless Love Song', kr: 'Nameless Love Song' },
    artist: 'Guilty Kiss',
    year: 2021,
    alias: ['네임리스 러브 송', '네임레스 러브 송', 'NLS'],
  },
  {
    id: 'A0137',
    name: { jp: 'OKAWARI Happy life!', kr: 'OKAWARI Happy life!' },
    artist: '타카미 치카',
    year: 2021,
    alias: ['오카와리 해피 라이프!'],
  },
  // A0138 moved to after A0022 for ordering
  {
    id: 'A0139',
    name: { jp: 'Love Spiral Tower', kr: 'Love Spiral Tower' },
    artist: '사쿠라우치 리코',
    year: 2021,
    alias: ['러브 스파이럴 타워', 'LST'],
  },
  {
    id: 'A0140',
    name: { jp: '1STAR', kr: '1STAR' },
    artist: '쿠로사와 루비',
    year: 2021,
    alias: ['원스타', '준장'],
  },
  {
    id: 'A0141',
    name: { jp: 'KU-RU-KU-RU Cruller!', kr: 'KU-RU-KU-RU Cruller!' },
    artist: 'Aqours',
    year: 2021,
    alias: ['크루크루 크룰러', '쿠루쿠루 크룰러', 'ㅋㅋㄹㅃㅃ'],
  },
  {
    id: 'A0142',
    name: { jp: 'SUKI for you, DREAM for you!', kr: 'SUKI for you, DREAM for you!' },
    artist: 'Aqours',
    year: 2021,
    alias: ['스키 포 유 드림 포 유'],
  },
];

// LOVELIVE_SUNSHINE_SONGS.forEach((song, idx) => {
//   if (LOVELIVE_SUNSHINE_SONGS.slice(idx + 1).findIndex((e) => e.id === song.id) > -1) {
//     throw Error(`Duplicate ID: ${song.id}`);
//   }
// });
