import { SongEntry } from './types';

// Aliases from: https://xn--hckp3ac2l023wu2ve.com/live-music-ryakushou-matome.html
export const LOVELIVE_SONGS: SongEntry[] = [
  {
    id: 'M0001',
    name: { jp: '僕らのLIVE 君とのLIFE', kr: '우리들의 LIVE 너와의 LIFE' },
    artist: 'μ’s',
    year: 2010,
    alias: ['보쿠라노 라이브 키미토노 라이프', '우리들의 라이브 너와의 라이프', '보라라라'],
  },
  {
    id: 'M0002',
    name: { jp: '友情ノーチェンジ', kr: '우정 노 체인지' },
    artist: 'μ’s',
    year: 2010,
    alias: ['노첸'],
  },
  {
    id: 'M0003',
    name: { jp: 'Snow halation', kr: 'Snow halation' },
    artist: 'μ’s',
    year: 2010,
    alias: ['스노우 하레이션', '스노 하레이션', '스노하레'],
  },
  {
    id: 'M0004',
    name: { jp: 'baby maybe 恋のボタン', kr: 'baby maybe 사랑의 버튼' },
    artist: 'μ’s',
    year: 2010,
    alias: ['베이비 메이비 코이노 보탄', '베이비 메이비 사랑의 버튼', '코이보타', '코이탄'],
  },
  {
    id: 'M0005',
    name: { jp: 'Love Marginal', kr: 'Love Marginal' },
    artist: 'Printemps',
    year: 2011,
    alias: ['러브 마지널', '러브 마지날', '러브마지'],
  },
  {
    id: 'M0006',
    name: { jp: 'sweet&sweet holiday', kr: 'sweet&sweet holiday' },
    artist: 'Printemps',
    year: 2011,
    alias: ['스윗&스윗 홀리데이', '스윗스윗 홀리데이', '스스홀', 'ssh'],
  },
  {
    id: 'M0007',
    name: { jp: 'ダイヤモンドプリンセスの憂鬱', kr: '다이아몬드 프린세스의 우울' },
    artist: 'BiBi',
    year: 2011,
    alias: ['다이프리'],
  },
  {
    id: 'M0008',
    name: { jp: 'ラブノベルス', kr: '러브 노벨즈' },
    artist: 'BiBi',
    year: 2011,
    alias: ['러브노베', '라부노베'],
  },
  {
    id: 'M0009',
    name: { jp: '知らないLove*教えてLove', kr: '모르겠어 Love*가르쳐줘 Love' },
    artist: 'lily white',
    year: 2011,
    alias: ['시라나이 Love 오시에떼 Love', '시라라라'],
  },
  {
    id: 'M0010',
    name: { jp: 'あ・の・ね・が・ん・ば・れ！', kr: '있・잖・아・힘・을・내!' },
    artist: 'lily white',
    year: 2011,
    alias: ['아노네 간바레', '아노네'],
  },
  {
    id: 'M0011',
    name: { jp: '夏色えがおで1,2,Jump!', kr: '여름빛 미소로 1,2,Jump!' },
    artist: 'μ’s',
    year: 2011,
    alias: ['나츠이로 에가오데 원투점프!', '나츠이로'],
  },
  {
    id: 'M0012',
    name: { jp: 'Mermaid festa vol.1', kr: 'Mermaid festa vol.1' },
    artist: 'μ’s',
    year: 2011,
    alias: ['머메이드 페스타 볼륨 1', '머메페스1', '마메페스1'],
  },
  {
    id: 'M0013',
    name: { jp: '私たちは未来の花', kr: '우리들은 미래의 꽃' },
    artist: '소노다 우미',
    year: 2011,
    alias: ['와타시타치와 미라이노 하나', '우미꽃', '와타하나'],
  },
  {
    id: 'M0014',
    name: { jp: 'スピカテリブル', kr: '스피카 테러블' },
    artist: '미나미 코토리',
    year: 2011,
    alias: ['스피카'],
  },
  {
    id: 'M0015',
    name: { jp: '愛は太陽じゃない？', kr: '사랑은 태양이 아닐까?' },
    artist: '코사카 호노카',
    year: 2012,
    alias: ['아이와 타이요오쟈 나이?', '아이타이'],
  },
  {
    id: 'M0016',
    name: { jp: 'もうひとりじゃないよ', kr: '더 이상 혼자가 아니야' },
    artist: '코사카 호노카',
    year: 2012,
    alias: ['모오 히토리쟈 나이요'],
  },
  {
    id: 'M0017',
    name: { jp: 'もぎゅっと“love”で接近中！', kr: '꼬옥 "love"로 접근 중!' },
    artist: 'μ’s',
    year: 2012,
    alias: ['모규', '모귯또', '러브개새끼'],
  },
  {
    id: 'M0018',
    name: { jp: '愛してるばんざーい！', kr: '사랑해 만세!' },
    artist: 'μ’s',
    year: 2012,
    alias: ['아이시떼루 반자이!', '반자이', '아이반', '아이반자'],
  },
  {
    id: 'M0019',
    name: { jp: 'Mermaid festa vol.2 ~Passionate~', kr: 'Mermaid festa vol.2 ~Passionate~' },
    artist: '코사카 호노카, 호시조라 린',
    year: 2012,
    alias: ['머메이드 페스타 볼륨 2', '머메페스2', '마메페스2'],
  },
  {
    id: 'M0020',
    name: { jp: 'Someday of my life', kr: 'Someday of my life' },
    artist: '코사카 호노카',
    year: 2012,
    alias: ['사무라이', '섬라이'],
  },
  {
    id: 'M0021',
    name: { jp: '恋のシグナルRin rin rin!', kr: '사랑의 시그널 Rin rin rin!' },
    artist: '호시조라 린',
    year: 2012,
    alias: ['린가베'],
  },
  {
    id: 'M0022',
    name: { jp: '乙女式れんあい塾', kr: '소녀식 연애 학원' },
    artist: '토죠 노조미, 야자와 니코',
    year: 2012,
    alias: ['소녀식', '지옥식'],
  },
  {
    id: 'M0023',
    name: { jp: 'まほうつかいはじめました！', kr: '마법사 시작했습니다!' },
    artist: '야자와 니코',
    year: 2012,
    alias: ['마법', '로드 오브 니코니'],
  },
  {
    id: 'M0024',
    name: { jp: '純愛レンズ', kr: '순애 렌즈' },
    artist: '토죠 노조미',
    year: 2012,
    alias: ['순애', '렌즈'],
  },
  {
    id: 'M0025',
    name: { jp: '告白日和、です！', kr: '고백하기 좋은 날, 이에요!' },
    artist: '미나미 코토리, 코이즈미 하나요',
    year: 2012,
    alias: ['고백일화'],
  },
  {
    id: 'M0026',
    name: { jp: 'ぶる~べりぃ♥とれいん', kr: '블루~베리♥트레인' },
    artist: '미나미 코토리',
    year: 2012,
    alias: ['블루베리 트레인', '트레인', '토레인', '블루토레', '브루토레', '부루토레', '블루베리'],
  },
  {
    id: 'M0027',
    name: { jp: '孤独なHeaven', kr: '고독한 Heaven' },
    artist: '코이즈미 하나요',
    year: 2012,
    alias: ['고독한 헤븐', '헤븐', '고독'],
  },
  {
    id: 'M0028',
    name: { jp: 'soldier game', kr: 'soldier game' },
    artist: '아야세 에리, 소노다 우미, 니시키노 마키',
    year: 2012,
    alias: ['소루게', '솔져 게임', '솔저 게임', '군인 놀이'],
  },
  {
    id: 'M0029',
    name: { jp: 'Daring!!', kr: 'Daring!!' },
    artist: '니시키노 마키',
    year: 2012,
    alias: ['다링!!', '달링!!'],
  },
  {
    id: 'M0030',
    name: { jp: '勇気のReason', kr: '용기의 Reason' },
    artist: '소노다 우미',
    year: 2012,
    alias: ['용기의 리즌'],
  },
  {
    id: 'M0031',
    name: { jp: 'ありふれた悲しみの果て', kr: '흔한 슬픔의 끝' },
    artist: '아야세 에리',
    year: 2012,
    alias: ['카나시미', '아리카나', '흔슬끝'],
  },
  {
    id: 'M0032',
    name: { jp: 'Wonderful Rush', kr: 'Wonderful Rush' },
    artist: 'μ’s',
    year: 2012,
    alias: ['원더풀 러쉬', '원더풀 러시', '원더런', '비행기', '이에니카엨챸타노'],
  },
  {
    id: 'M0033',
    name: { jp: 'Oh,Love＆Peace!', kr: 'Oh,Love＆Peace!' },
    artist: 'μ’s',
    year: 2012,
    alias: ['러브 앤 피스', '러브피'],
  },
  {
    id: 'M0034',
    name: { jp: 'Listen to my heart!!', kr: 'Listen to my heart!!' },
    artist: '호시조라 린, 코이즈미 하나요, 야자와 니코',
    year: 2012,
    alias: ['리슨 투 마이 하트!!', '리스마이', 'Ltmh'],
  },
  {
    id: 'M0035',
    name: { jp: 'after school NAVIGATORS', kr: 'after school NAVIGATORS' },
    artist: '호시조라 린, 코이즈미 하나요, 야자와 니코',
    year: 2012,
    alias: ['애프터 스쿨 내비게이터스', 'asN', '방과후'],
  },
  {
    id: 'M0036',
    name: { jp: '僕らは今のなかで', kr: '우리들은 지금 속에서' },
    artist: 'μ’s',
    year: 2013,
    alias: ['보쿠라와 이마노 나카데', '보쿠이마'],
  },
  {
    id: 'M0037',
    name: { jp: 'WILD STARS', kr: 'WILD STARS' },
    artist: 'μ’s',
    year: 2013,
    alias: ['와일드 스타즈', '와이스타'],
  },
  {
    id: 'M0038',
    name: { jp: 'きっと青春が聞こえる', kr: '분명 청춘이 들릴 거야' },
    artist: 'μ’s',
    year: 2013,
    alias: ['킷토 세이슌가 키코에루'],
  },
  {
    id: 'M0039',
    name: { jp: '輝夜の城で踊りたい', kr: '카구야의 성에서 춤추고 싶어' },
    artist: 'μ’s',
    year: 2013,
    alias: ['콜법관'],
  },
  {
    id: 'M0040',
    name: { jp: 'ススメ→トゥモロウ', kr: '나아가→Tomorrow' },
    artist: '코사카 호노카, 미나미 코토리, 소노다 우미',
    year: 2013,
    alias: ['스스메 투모로우'],
  },
  {
    id: 'M0041',
    name: { jp: 'START:DASH!!', kr: 'START:DASH!!' },
    artist: '코사카 호노카, 미나미 코토리, 소노다 우미',
    year: 2013,
    alias: ['스타트 대시!!', '스타트 대쉬!!', '스타다'],
  },
  {
    id: 'M0042',
    name: { jp: 'これからのSomeday', kr: '앞으로 다가올 Someday' },
    artist: '코사카 호노카, 미나미 코토리, 소노다 우미, 호시조라 린, 니시키노 마키, 코이즈미 하나요, 야자와 니코',
    year: 2013,
    alias: ['코레카라노 섬데이', '앞으로 다가올 섬데이', '코레섬데', '코레사무'],
  },
  {
    id: 'M0043',
    name: { jp: 'Wonder zone', kr: 'Wonder zone' },
    artist: 'μ’s',
    year: 2013,
    alias: ['원더 존', 'WZ'],
  },
  {
    id: 'M0044',
    name: { jp: 'No brand girls', kr: 'No brand girls' },
    artist: 'μ’s',
    year: 2013,
    alias: ['노 브랜드 걸스', '노 브랜드 걸즈', '노브라', '노브랜'],
  },
  {
    id: 'M0045',
    name: { jp: 'START:DASH!! (μ’s)', kr: 'START:DASH!! (μ’s)' },
    artist: 'μ’s',
    year: 2013,
    alias: ['스타트 대시!!', '스타트 대쉬!!', '스타다'],
    excludable: true,
  },
  {
    id: 'M0046',
    name: { jp: '夢なき夢は夢じゃない', kr: '꿈이 없는 꿈은 꿈이 아니야' },
    artist: '코사카 호노카',
    year: 2013,
    alias: ['파이토다요', '유메유메유메', '꿈꿈꿈', '꿈3'],
  },
  {
    id: 'M0047',
    name: { jp: 'Anemone heart', kr: 'Anemone heart' },
    artist: '미나미 코토리, 소노다 우미',
    year: 2013,
    alias: ['아네모네 하트'],
  },
  {
    id: 'M0048',
    name: { jp: 'なわとび', kr: '줄넘기' },
    artist: '코이즈미 하나요',
    year: 2013,
    alias: ['나와토비'],
  },
  {
    id: 'M0049',
    name: { jp: 'Beat in Angel', kr: 'Beat in Angel' },
    artist: '호시조라 린, 니시키노 마키',
    year: 2013,
    alias: ['비트 인 엔젤', '빗 인 엔젤', 'BiA', '마지엔젤'],
  },
  {
    id: 'M0050',
    name: { jp: 'にこぷり♡女子道', kr: '니코프리♡여자의 길' },
    artist: '야자와 니코',
    year: 2013,
    alias: ['니코프리 니코니코'],
  },
  {
    id: 'M0051',
    name: { jp: '硝子の花園', kr: '유리의 화원' },
    artist: '아야세 에리, 토죠 노조미',
    year: 2013,
    alias: ['살메히망', '노조에리'],
  },
  {
    id: 'M0052',
    name: { jp: 'LONELIEST BABY', kr: 'LONELIEST BABY' },
    artist: 'μ’s',
    year: 2013,
    alias: ['론리스트 베이비', 'LB'],
  },
  {
    id: 'M0053',
    name: { jp: 'ぷわぷわーお！', kr: '푹신푹신-오!' },
    artist: 'Printemps',
    year: 2013,
    alias: ['뿌와뿌와오', '푸와푸와오', '후시기다요', '키미니 톤데케 스키스키 뿌와뿌와'],
  },
  {
    id: 'M0054',
    name: { jp: '微熱からMystery', kr: '미열에서 Mystery' },
    artist: 'lily white',
    year: 2013,
    alias: ['미열에서 미스테리', '미열미스'],
  },
  {
    id: 'M0055',
    name: { jp: 'キミのくせに！', kr: '너 주제에!' },
    artist: 'lily white',
    year: 2013,
    alias: ['키미노 쿠세니!'],
  },
  {
    id: 'M0056',
    name: { jp: 'Cutie Panther', kr: 'Cutie Panther' },
    artist: 'BiBi',
    year: 2013,
    alias: ['큐티 팬서', 'CP', '큐티판'],
  },
  {
    id: 'M0057',
    name: { jp: '夏、終わらないで。', kr: '여름, 끝나지 말아줘.' },
    artist: 'BiBi',
    year: 2013,
    alias: ['나츠오와'],
  },
  {
    id: 'M0058',
    name: { jp: 'Pure girls project', kr: 'Pure girls project' },
    artist: 'Printemps',
    year: 2013,
    alias: ['퓨어 걸즈 프로젝트', '퓨어 걸스 프로젝트', 'Pgp'],
  },
  {
    id: 'M0059',
    name: { jp: 'UNBALANCED LOVE', kr: 'UNBALANCED LOVE' },
    artist: 'Printemps',
    year: 2013,
    alias: ['언밸런스드 러브', '언바라'],
  },
  {
    id: 'M0060',
    name: { jp: 'Music S.T.A.R.T!!', kr: 'Music S.T.A.R.T!!' },
    artist: 'μ’s',
    year: 2013,
    alias: ['뮤직 스타트!', 'M스타', '이 노래에 어서와'],
  },
  {
    id: 'M0061',
    name: { jp: 'LOVELESS WORLD', kr: 'LOVELESS WORLD' },
    artist: 'μ’s',
    year: 2013,
    alias: ['러브리스 월드', '러브레스 월드', '러브레스'],
  },
  {
    id: 'M0062',
    name: { jp: 'タカラモノズ', kr: '보물들' },
    artist: 'μ’s',
    year: 2014,
    alias: ['타카라모노즈'],
  },
  {
    id: 'M0063',
    name: { jp: 'Paradise Live', kr: 'Paradise Live' },
    artist: 'μ’s',
    year: 2014,
    alias: ['파라다이스 라이브', '파라라이', 'PL'],
  },
  {
    id: 'M0064',
    name: { jp: 'それは僕たちの奇跡', kr: '그것은 우리들의 기적' },
    artist: 'μ’s',
    year: 2014,
    alias: ['소레키세'],
  },
  {
    id: 'M0065',
    name: { jp: 'だってだって噫無情', kr: '그치만 그치만 아아 무정' },
    artist: 'μ’s',
    year: 2014,
    alias: ['아무정'],
  },
  {
    id: 'M0066',
    name: { jp: 'どんなときもずっと', kr: '어떤 때라도 계속' },
    artist: 'μ’s',
    year: 2014,
    alias: ['돈토키', '모즛토'],
  },
  {
    id: 'M0067',
    name: { jp: 'COLORFUL VOICE', kr: 'COLORFUL VOICE' },
    artist: 'μ’s',
    year: 2014,
    alias: ['컬러풀 보이스', '카라보'],
  },
  {
    id: 'M0068',
    name: { jp: 'ユメノトビラ', kr: '꿈의 문' },
    artist: 'μ’s',
    year: 2014,
    alias: ['유메노 토비라', '유메토비'],
  },
  {
    id: 'M0069',
    name: { jp: 'SENTIMENTAL StepS', kr: 'SENTIMENTAL StepS' },
    artist: 'μ’s',
    year: 2014,
    alias: ['센티멘탈 스텝스', 'SSS'],
  },
  {
    id: 'M0070',
    name: { jp: 'Love wing bell', kr: 'Love wing bell' },
    artist: '아야세 에리, 호시조라 린, 니시키노 마키, 토죠 노조미, 코이즈미 하나요, 야자와 니코',
    year: 2014,
    alias: ['럽윙벨', '윙가베'],
  },
  {
    id: 'M0071',
    name: { jp: 'Dancing stars on me!', kr: 'Dancing stars on me!' },
    artist: 'μ’s',
    year: 2014,
    alias: ['댄싱 스타스 온 미!', '댄싱 스타즈 온 미!', '단스타'],
  },
  {
    id: 'M0072',
    name: { jp: 'KiRa-KiRa Sensation!', kr: 'KiRa-KiRa Sensation!' },
    artist: 'μ’s',
    year: 2014,
    alias: ['키라키라 센세이션!', '키라센'],
  },
  {
    id: 'M0073',
    name: { jp: 'Happy maker!', kr: 'Happy maker!' },
    artist: 'μ’s',
    year: 2014,
    alias: ['해피 메이커!', '하피메'],
  },
  {
    id: 'M0074',
    name: { jp: 'シアワセ行きのSMILING!', kr: '행복을 향한 SMILING!' },
    artist: '코사카 호노카',
    year: 2014,
    alias: ['행복을 향한 스마일링!', '스마일링'],
  },
  {
    id: 'M0075',
    name: { jp: 'ずるいよMagnetic today', kr: '치사해 Magnetic today' },
    artist: '니시키노 마키, 야자와 니코',
    year: 2014,
    alias: ['자석', '니코마키'],
  },
  {
    id: 'M0076',
    name: { jp: 'くるりんMIRACLE', kr: '빙그르르 MIRACLE' },
    artist: '호시조라 린',
    year: 2014,
    alias: ['쿠루미라'],
  },
  {
    id: 'M0077',
    name: { jp: 'Storm in Lover', kr: 'Storm in Lover' },
    artist: '아야세 에리, 소노다 우미',
    year: 2014,
    alias: ['스톰 인 러버', '스토라바', '머메3'],
  },
  {
    id: 'M0078',
    name: { jp: 'もしもからきっと', kr: '만약으로부터 분명' },
    artist: '토죠 노조미',
    year: 2014,
    alias: ['모시모카라 킷토', '모시모'],
  },
  {
    id: 'M0079',
    name: { jp: '好きですが好きですか？', kr: '좋아하는데 좋아하나요?' },
    artist: '미나미 코토리, 코이즈미 하나요',
    year: 2014,
    alias: ['스키스키'],
  },
  {
    id: 'M0080',
    name: { jp: 'そして最後のページには', kr: '그리고 마지막 페이지에는' },
    artist: 'μ’s',
    year: 2014,
    alias: ['소시페'],
  },
  {
    id: 'M0081',
    name: { jp: 'CheerDay CheerGirl!', kr: 'CheerDay CheerGirl!' },
    artist: 'Printemps',
    year: 2014,
    alias: ['치어데이 치어걸!'],
  },
  {
    id: 'M0082',
    name: { jp: 'Silent tonight', kr: 'Silent tonight' },
    artist: 'BiBi',
    year: 2014,
    alias: ['사일런트 투나잇', 'St'],
  },
  {
    id: 'M0083',
    name: { jp: '同じ星が見たい', kr: '같은 별이 보고 싶어' },
    artist: 'lily white',
    year: 2014,
    alias: ['오나지 호시가 미타이'],
  },
  {
    id: 'M0084',
    name: { jp: 'Shangri-La Shower', kr: 'Shangri-La Shower' },
    artist: 'μ’s',
    year: 2014,
    alias: ['샹그리라 샤워', '샹샤워'],
  },
  {
    id: 'M0085',
    name: { jp: 'るてしキスキしてる', kr: '해아좋아해' },
    artist: 'μ’s',
    year: 2014,
    alias: ['루테시키스키시테루', '루테시'],
  },
  {
    id: 'M0086',
    name: { jp: '永遠フレンズ', kr: '영원 프렌즈' },
    artist: 'Printemps',
    year: 2014,
    alias: [],
  },
  {
    id: 'M0087',
    name: { jp: '小夜啼鳥恋詩', kr: '나이팅게일 러브송' },
    artist: 'Printemps',
    year: 2014,
    alias: ['나이러브', '나이팅'],
  },
  {
    id: 'M0088',
    name: { jp: '秋のあなたの空遠く', kr: '가을의 당신의 하늘 저 멀리' },
    artist: 'lily white',
    year: 2014,
    alias: ['아키소라'],
  },
  {
    id: 'M0089',
    name: { jp: 'ふたりハピネス', kr: '두 사람 해피니스' },
    artist: 'lily white',
    year: 2014,
    alias: ['후타리 하피네스', '후타리 해피니스'],
  },
  {
    id: 'M0090',
    name: { jp: '冬がくれた予感', kr: '겨울이 준 예감' },
    artist: 'BiBi',
    year: 2014,
    alias: ['후유요칸', '후유쿠레'],
  },
  {
    id: 'M0091',
    name: { jp: 'Trouble Busters', kr: 'Trouble Busters' },
    artist: 'BiBi',
    year: 2014,
    alias: ['트러블 버스터즈', '토라바스'],
  },
  {
    id: 'M0092',
    name: { jp: 'ミはμ’sicのミ', kr: '미는 μ’sic의 미' },
    artist: 'μ’s',
    year: 2015,
    alias: ['미는 뮤직의 미', '미뮤미', '미미미'],
  },
  {
    id: 'M0093',
    name: { jp: 'Super LOVE＝Super LIVE!', kr: 'Super LOVE＝Super LIVE!' },
    artist: 'μ’s',
    year: 2015,
    alias: ['슈퍼 러브 슈퍼 라이브', '슈라슈라', '스파라라', '스파라이'],
  },
  {
    id: 'M0094',
    name: { jp: 'Angelic Angel', kr: 'Angelic Angel' },
    artist: 'μ’s',
    year: 2015,
    alias: ['엔젤릭 엔젤', 'AA', '극센에'],
  },
  {
    id: 'M0095',
    name: { jp: 'Hello，星を数えて', kr: 'Hello, 별을 세며' },
    artist: '호시조라 린, 니시키노 마키, 코이즈미 하나요',
    year: 2015,
    alias: ['헬로호시', '하로호시', 'H호시'],
  },
  {
    id: 'M0096',
    name: { jp: 'SUNNY DAY SONG', kr: 'SUNNY DAY SONG' },
    artist: 'μ’s',
    year: 2015,
    alias: ['서니데이 송', '스드스', 'SDS', '서니송'],
  },
  {
    id: 'M0097',
    name: { jp: '？←HEARTBEAT', kr: '？←HEARTBEAT' },
    artist: '아야세 에리, 토죠 노조미, 야자와 니코',
    year: 2015,
    alias: ['하테나 하트비트', '하토비'],
  },
  {
    id: 'M0098',
    name: { jp: '僕たちはひとつの光', kr: '우리는 하나의 빛' },
    artist: 'μ’s',
    year: 2015,
    alias: ['우리들은 하나의 빛', '보쿠타치와 히토츠노 히카리', '보쿠히카', '눈물벨', 'ZAQ갓'],
  },
  {
    id: 'M0099',
    name: { jp: 'Future style', kr: 'Future style' },
    artist: '코사카 호노카, 미나미 코토리, 소노다 우미',
    year: 2015,
    alias: ['퓨쳐 스타일', 'Fs', 'F스타'],
  },
  {
    id: 'M0100',
    name: { jp: 'これから', kr: '지금부터' },
    artist: 'μ’s',
    year: 2015,
    alias: ['코레카라'],
  },
  {
    id: 'M0101',
    name: { jp: 'MUSEUMでどうしたい？', kr: 'MUSEUM에서 뭘하고 싶어?' },
    artist: 'Printemps',
    year: 2015,
    alias: [],
  },
  {
    id: 'M0102',
    name: { jp: '乙姫心で恋宮殿', kr: '용녀 마음으로 사랑 궁전' },
    artist: 'lily white',
    year: 2015,
    alias: [],
  },
  {
    id: 'M0103',
    name: { jp: '最低で最高のParadiso', kr: '최저이자 최고의 Paradiso' },
    artist: 'BiBi',
    year: 2015,
    alias: [],
  },
  {
    id: 'M0104',
    name: { jp: 'HEART to HEART!', kr: 'HEART to HEART!' },
    artist: 'μ’s',
    year: 2015,
    alias: ['하트 투 하트!', 'HtH'],
  },
  {
    id: 'M0105',
    name: { jp: '嵐のなかの恋だから', kr: '폭풍 속의 사랑이니까' },
    artist: 'μ’s',
    year: 2015,
    alias: ['아라코이'],
  },
  {
    id: 'M0106',
    name: { jp: 'WAO-WAO Powerful day!', kr: 'WAO-WAO Powerful day!' },
    artist: 'Printemps',
    year: 2015,
    alias: ['와오와오'],
  },
  {
    id: 'M0107',
    name: { jp: 'NO EXIT ORION', kr: 'NO EXIT ORION' },
    artist: 'Printemps',
    year: 2015,
    alias: ['NEO', '오리온', '얀데레'],
  },
  {
    id: 'M0108',
    name: { jp: '思い出以上になりたくて', kr: '추억 이상이 되고 싶어서' },
    artist: 'lily white',
    year: 2015,
    alias: ['오모이데'],
  },
  {
    id: 'M0109',
    name: { jp: '春情ロマンティック', kr: '춘정 로맨틱' },
    artist: 'lily white',
    year: 2015,
    alias: [],
  },
  {
    id: 'M0110',
    name: { jp: '錯覚CROSSROADS', kr: '착각 CROSSROADS' },
    artist: 'BiBi',
    year: 2016,
    alias: ['착각 크로스로드'],
  },
  {
    id: 'M0111',
    name: { jp: 'PSYCHIC FIRE', kr: 'PSYCHIC FIRE' },
    artist: 'BiBi',
    year: 2016,
    alias: ['사이킥 파이어', 'PF', '사이킥', '사이파이'],
  },
  {
    id: 'M0112',
    name: { jp: 'MOMENT RING', kr: 'MOMENT RING' },
    artist: 'μ’s',
    year: 2016,
    alias: ['모멘트 링', '모먼트 링', '모메링'],
  },
  {
    id: 'M0113',
    name: { jp: 'さようならへさよなら！', kr: '안녕이란 말에 안녕!' },
    artist: 'μ’s',
    year: 2016,
    alias: ['사요나라에 사요나라!', '사요사요'],
  },
  {
    id: 'M0114',
    name: { jp: 'A song for You! You? You!!', kr: 'A song for You! You? You!!' },
    artist: 'μ’s',
    year: 2020,
    alias: ['송 포 유유유'],
  },
  {
    id: 'M0115',
    name: { jp: 'なってしまった！', kr: '되어버렸어!' },
    artist: 'μ’s',
    year: 2020,
    alias: ['낫테시맛타!'],
  },
  {
    id: 'M0116',
    name: { jp: 'ENDLESS PARADE', kr: 'ENDLESS PARADE' },
    artist: 'μ’s',
    year: 2014,
    alias: ['엔들레스 퍼레이드', '엔들리스 퍼레이드', '엔파레'],
  },
  {
    id: 'M0117',
    name: { jp: 'Dreamin\' Go! Go!!', kr: 'Dreamin\' Go! Go!!' },
    artist: 'μ’s',
    year: 2015,
    alias: ['도리고', '드리밍'],
  },
  {
    id: 'M0118',
    name: { jp: 'Private Wars', kr: 'Private Wars' },
    artist: 'A-RISE',
    year: 2013,
    alias: ['프라이빗 워', '와챠두'],
  },
  {
    id: 'M0119',
    name: { jp: 'Shocking Party', kr: 'Shocking Party' },
    artist: 'A-RISE',
    year: 2014,
    alias: ['쇼킹 파티', '파리쇼킹파리', '쇼쿠파'],
  },
];

// LOVELIVE_SONGS.forEach((song, idx) => {
//   if (LOVELIVE_SONGS.slice(idx + 1).findIndex((e) => e.id === song.id) > -1) {
//     throw Error(`Duplicate ID: ${song.id}`);
//   }
// });
