import { SongEntry } from './types';

export const LOVELIVE_NIJI_SONGS: SongEntry[] = [
  {
    id: 'N0001',
    name: { jp: 'TOKIMEKI Runners', kr: 'TOKIMEKI Runners' },
    artist: '니지가사키 학원 스쿨 아이돌 동호회',
    year: 2018,
    alias: ['토키메키 러너즈', '도키메키 러너즈', '토키런', '토키란', '도키런', '도키란'],
  },
  {
    id: 'N0002',
    name: { jp: '夢への一歩', kr: '꿈으로의 한 걸음' },
    artist: '우에하라 아유무',
    year: 2018,
    alias: ['유메잇뽀'],
  },
  {
    id: 'N0003',
    name: { jp: 'ダイアモンド', kr: '다이아몬드' },
    artist: '나카스 카스미',
    year: 2018,
    alias: [],
  },
  {
    id: 'N0004',
    name: { jp: 'あなたの理想のヒロイン', kr: '당신의 이상적인 히로인' },
    artist: '오사카 시즈쿠',
    year: 2018,
    alias: ['아나타노 리소오노 히로인'],
  },
  {
    id: 'N0005',
    name: { jp: 'Starlight', kr: 'Starlight' },
    artist: '아사카 카린',
    year: 2018,
    alias: ['스타라이트'],
  },
  {
    id: 'N0006',
    name: { jp: 'めっちゃGoing!!', kr: '엄청 Going!!' },
    artist: '미야시타 아이',
    year: 2018,
    alias: ['멧챠 고잉!!', '엄청 고잉!!', '존나 고잉!!'],
  },
  {
    id: 'N0007',
    name: { jp: '眠れる森に行きたいな', kr: '잠자는 숲 속으로 가고 싶어' },
    artist: '코노에 카나타',
    year: 2018,
    alias: ['네무레루 모리니 이키타이나'],
  },
  {
    id: 'N0008',
    name: { jp: 'CHASE!', kr: 'CHASE!' },
    artist: '유키 세츠나',
    year: 2018,
    alias: ['체이스!'],
  },
  {
    id: 'N0009',
    name: { jp: 'Evergreen', kr: 'Evergreen' },
    artist: '엠마 베르데',
    year: 2018,
    alias: ['에버그린'],
  },
  {
    id: 'N0010',
    name: { jp: 'ドキピポ☆エモーション', kr: '도키피포☆이모션' },
    artist: '텐노지 리나',
    year: 2018,
    alias: ['도키피포 이모션'],
  },
  {
    id: 'N0011',
    name: { jp: '開花宣言', kr: '개화선언' },
    artist: '우에하라 아유무',
    year: 2019,
    alias: [],
  },
  {
    id: 'N0012',
    name: { jp: '☆ワンダーランド☆', kr: '☆원더랜드☆' },
    artist: '나카스 카스미',
    year: 2019,
    alias: [],
  },
  {
    id: 'N0013',
    name: { jp: 'オードリー', kr: '오드리' },
    artist: '오사카 시즈쿠',
    year: 2019,
    alias: ['오도리'],
  },
  {
    id: 'N0014',
    name: { jp: 'Wish', kr: 'Wish' },
    artist: '아사카 카린',
    year: 2019,
    alias: ['위시', '위쉬', '소원'],
  },
  {
    id: 'N0015',
    name: { jp: '友 & 愛', kr: '친구 & 사랑' },
    artist: '미야시타 아이',
    year: 2019,
    alias: ['유앤아이'],
  },
  {
    id: 'N0016',
    name: { jp: 'My Own Fairy-Tale', kr: 'My Own Fairy-Tale' },
    artist: '코노에 카나타',
    year: 2019,
    alias: ['MOFT'],
  },
  {
    id: 'N0017',
    name: { jp: 'MELODY', kr: 'MELODY' },
    artist: '유키 세츠나',
    year: 2019,
    alias: ['멜로디'],
  },
  {
    id: 'N0018',
    name: { jp: '声繋ごうよ', kr: '목소리를 잇자' },
    artist: '엠마 베르데',
    year: 2019,
    alias: ['코에츠나'],
  },
  {
    id: 'N0019',
    name: { jp: 'テレテレパシー', kr: '텔레텔레파시' },
    artist: '텐노지 리나',
    year: 2019,
    alias: ['테레테레파시'],
  },
  {
    id: 'N0020',
    name: { jp: 'Love U my friends', kr: 'Love U my friends' },
    artist: '니지가사키 학원 스쿨 아이돌 동호회',
    year: 2019,
    alias: ['러브 유 마이 프렌즈', '럽마프', 'LUmf'],
  },
  {
    id: 'N0021',
    name: { jp: 'SUPER NOVA', kr: 'SUPER NOVA' },
    artist: 'DiverDiva',
    year: 2020,
    alias: ['슈퍼 노바', '수퍼 노바'],
  },
  {
    id: 'N0022',
    name: { jp: 'Love Triangle', kr: 'Love Triangle' },
    artist: 'DiverDiva',
    year: 2020,
    alias: ['러브 트라이앵글', 'LT'],
  },
  {
    id: 'N0023',
    name: { jp: 'Dream Land！Dream World！', kr: 'Dream Land！Dream World！' },
    artist: 'A・ZU・NA',
    year: 2020,
    alias: ['Dream Land! Dream World!', '드림 랜드! 드림 월드!', 'DLDW'],
  },
  {
    id: 'N0024',
    name: { jp: 'Cheer for you!!', kr: 'Cheer for you!!' },
    artist: 'A・ZU・NA',
    year: 2020,
    alias: ['치어 포 유', 'Cfy'],
  },
  {
    id: 'N0025',
    name: { jp: 'Sing & Smile!!', kr: 'Sing & Smile!!' },
    artist: 'QU4RTZ',
    year: 2020,
    alias: ['싱 앤 스마일!!', 'SaS', 'SnS'],
  },
  {
    id: 'N0026',
    name: { jp: 'Beautiful Moonlight', kr: 'Beautiful Moonlight' },
    artist: 'QU4RTZ',
    year: 2020,
    alias: ['뷰티풀 문라이트', '뷰티풀 문라잇', 'BM'],
  },
  {
    id: 'N0027',
    name: { jp: '無敵級*ビリーバー', kr: '무적급*빌리버' },
    artist: '나카스 카스미',
    year: 2020,
    alias: ['무적급 빌리버'],
  },
  {
    id: 'N0028',
    name: { jp: '未来ハーモニー', kr: '미래 하모니' },
    artist: '니지가사키 학원 스쿨 아이돌 동호회',
    year: 2020,
    alias: ['미라이 하모니'],
  },
  {
    id: 'N0029',
    name: { jp: 'Say Good-Bye 涙', kr: 'Say Good-Bye 눈물' },
    artist: '우에하라 아유무',
    year: 2020,
    alias: ['세이 굿바이 나미다', '세굿바', 'SGB'],
  },
  {
    id: 'N0030',
    name: { jp: 'Margaret', kr: 'Margaret' },
    artist: '나카스 카스미',
    year: 2020,
    alias: ['마가렛'],
  },
  {
    id: 'N0031',
    name: { jp: 'やがてひとつの物語', kr: '이윽고 하나의 이야기' },
    artist: '오사카 시즈쿠',
    year: 2020,
    alias: ['마침내 하나의 이야기', '야가히토'],
  },
  {
    id: 'N0032',
    name: { jp: 'Fire Bird', kr: 'Fire Bird' },
    artist: '아사카 카린',
    year: 2020,
    alias: ['파이어 버드', '불새'],
  },
  {
    id: 'N0033',
    name: { jp: '楽しいの天才', kr: '즐거움의 천재' },
    artist: '미야시타 아이',
    year: 2020,
    alias: ['타노시이노 텐사이'],
  },
  {
    id: 'N0034',
    name: { jp: 'Märchen Star', kr: 'Märchen Star' },
    artist: '코노에 카나타',
    year: 2020,
    alias: ['메르헨 스타', 'Marchen Star'],
  },
  {
    id: 'N0035',
    name: { jp: 'LIKE IT！LOVE IT！', kr: 'LIKE IT！LOVE IT！' },
    artist: '유키 세츠나',
    year: 2020,
    alias: ['LIKE IT! LOVE IT!', '라이크 잇 러브 잇', 'LILI'],
  },
  {
    id: 'N0036',
    name: { jp: '哀温ノ詩', kr: '애온의 시' },
    artist: '엠마 베르데',
    year: 2020,
    alias: [],
  },
  {
    id: 'N0037',
    name: { jp: 'アナログハート', kr: '아날로그 하트' },
    artist: '텐노지 리나',
    year: 2020,
    alias: [],
  },
  {
    id: 'N0038',
    name: { jp: '決意の光', kr: '결의의 빛' },
    artist: '미후네 시오리코',
    year: 2020,
    alias: ['결빛'],
  },
  {
    id: 'N0039',
    name: { jp: 'TOKIMEKI Runners（スクスタストーリー17章挿入歌Ver.）', kr: 'TOKIMEKI Runners (스쿠스타 스토리 17장 삽입곡Ver.)' },
    artist: '니지가사키 학원 스쿨 아이돌 동호회',
    year: 2020,
    alias: ['토키메키 러너즈', '도키메키 러너즈', '토키런', '토키란', '도키런', '도키란'],
  },
  {
    id: 'N0040',
    name: { jp: 'Just Believe!!!', kr: 'Just Believe!!!' },
    artist: '니지가사키 학원 스쿨 아이돌 동호회',
    year: 2020,
    alias: ['저스트 빌리브!!!', '믿기본', 'ㅁㄱㅂ'],
  },
  {
    id: 'N0041',
    name: { jp: '虹色Passions！', kr: '무지갯빛 Passions!' },
    artist: '니지가사키 학원 스쿨 아이돌 동호회',
    year: 2020,
    alias: ['니지이로 패션즈!', '니지패션'],
  },
  {
    id: 'N0042',
    name: { jp: 'Sweet Eyes', kr: 'Sweet Eyes' },
    artist: '니지가사키 학원 스쿨 아이돌 동호회',
    year: 2020,
    alias: ['스윗 아이즈', '스위트 아이즈', '달콤눈'],
  },
  {
    id: 'N0043',
    name: { jp: 'NEO SKY, NEO MAP!', kr: 'NEO SKY, NEO MAP!' },
    artist: '니지가사키 학원 스쿨 아이돌 동호회',
    year: 2020,
    alias: ['네오 스카이 네오 맵!', '네오네오', 'ㄴㅇㄴㅇㅇㄷㅇㅇㄴㅇㄴㅇ'],
  },
  {
    id: 'N0044',
    name: { jp: '全速ドリーマー', kr: '전속 드리머' },
    artist: '니지가사키 학원 스쿨 아이돌 동호회',
    year: 2020,
    alias: [],
  },
  {
    id: 'N0045',
    name: { jp: 'Dream with You', kr: 'Dream with You' },
    artist: '우에하라 아유무',
    year: 2020,
    alias: ['드림 윗 유', '드림 위드 유'],
  },
  {
    id: 'N0046',
    name: { jp: 'Poppin\' Up!', kr: 'Poppin\' Up!' },
    artist: '나카스 카스미',
    year: 2020,
    alias: ['포핀 업!'],
  },
  {
    id: 'N0047',
    name: { jp: 'DIVE！', kr: 'DIVE！' },
    artist: '유키 세츠나',
    year: 2020,
    alias: ['DIVE!'],
  },
  {
    id: 'N0048',
    name: { jp: 'サイコーハート', kr: '사이코 하트' },
    artist: '미야시타 아이',
    year: 2020,
    alias: ['최고 하트'],
  },
  {
    id: 'N0049',
    name: { jp: 'La Bella Patria', kr: 'La Bella Patria' },
    artist: '엠마 베르데',
    year: 2020,
    alias: ['라 벨라 파트리아', '라벨파', 'LBP'],
  },
  {
    id: 'N0050',
    name: { jp: 'ツナガルコネクト', kr: '이어지는 커넥트' },
    artist: '텐노지 리나',
    year: 2020,
    alias: ['츠나가루 커넥트', '츠나코네'],
  },
  {
    id: 'N0051',
    name: { jp: 'Butterfly', kr: 'Butterfly' },
    artist: '코노에 카나타',
    year: 2020,
    alias: ['버터플라이', '나비'],
  },
  {
    id: 'N0052',
    name: { jp: 'Solitude Rain', kr: 'Solitude Rain' },
    artist: '오사카 시즈쿠',
    year: 2020,
    alias: ['솔리튜드 레인'],
  },
  {
    id: 'N0053',
    name: { jp: 'VIVID WORLD', kr: 'VIVID WORLD' },
    artist: '아사카 카린',
    year: 2020,
    alias: ['비비드 월드', '선명한 세계'],
  },
  {
    id: 'N0054',
    name: { jp: 'Awakening Promise', kr: 'Awakening Promise' },
    artist: '우에하라 아유무',
    year: 2021,
    alias: ['어웨이크닝 프라미스', '어웨이크닝 프로미스'],
  },
  {
    id: 'N0055',
    name: { jp: '夢がここからはじまるよ', kr: '꿈이 이곳에서부터 시작돼' },
    artist: '니지가사키 학원 스쿨 아이돌 동호회',
    year: 2021,
    alias: ['유메가 코코카라 하지마루요', '유메코코'],
  },
  {
    id: 'N0056',
    name: { jp: 'POWER SPOT!!', kr: 'POWER SPOT!!' },
    artist: 'DiverDiva',
    year: 2020,
    alias: ['파워 스팟!!'],
  },
  {
    id: 'N0057',
    name: { jp: 'Kakushiaji!', kr: 'Kakushiaji!' },
    artist: 'A・ZU・NA',
    year: 2021,
    alias: ['카쿠시아지'],
  },
  {
    id: 'N0058',
    name: { jp: 'Make-up session ABC', kr: 'Make-up session ABC' },
    artist: 'QU4RTZ',
    year: 2021,
    alias: ['메이크 업 세션 에이비씨'],
  },
  {
    id: 'N0059',
    name: { jp: '祭花 -saika-', kr: '제화 -saika-' },
    artist: 'DiverDiva',
    year: 2021,
    alias: [],
  },
  {
    id: 'N0060',
    name: { jp: 'Happy Nyan! Days', kr: 'Happy Nyan! Days' },
    artist: 'A・ZU・NA',
    year: 2021,
    alias: ['해피 냥 데이즈'],
  },
  {
    id: 'N0061',
    name: { jp: 'Twinkle Town', kr: 'Twinkle Town' },
    artist: 'QU4RTZ',
    year: 2021,
    alias: ['트윙클 타운'],
  },
  {
    id: 'N0062',
    name: { jp: 'Hurray Hurray', kr: 'Hurray Hurray' },
    artist: '니지가사키 학원 스쿨 아이돌 동호회',
    year: 2021,
    alias: ['트윙클 타운'],
  },
  {
    id: 'N0063',
    name: { jp: 'THE SECRET NiGHT', kr: 'THE SECRET NiGHT' },
    artist: 'DiverDiva',
    year: 2021,
    alias: ['더 시크릿 나잇'],
  },
  {
    id: 'N0064',
    name: { jp: 'Fly into the sky', kr: 'Fly into the sky' },
    artist: 'DiverDiva',
    year: 2021,
    alias: [],
  },
  {
    id: 'N0065',
    name: { jp: 'Maze Town', kr: 'Maze Town' },
    artist: 'A・ZU・NA',
    year: 2021,
    alias: ['메이즈 타운'],
  },
  {
    id: 'N0066',
    name: { jp: 'フォルクロア ～歓喜の歌～', kr: '포크로어 ~환희의 노래~' },
    artist: 'A・ZU・NA',
    year: 2021,
    alias: [],
  },
  {
    id: 'N0067',
    name: { jp: 'Swinging！', kr: 'Swinging！' },
    artist: 'QU4RTZ',
    year: 2021,
    alias: ['Swinging!', '스윙잉', '스윙깅'],
  },
  {
    id: 'N0068',
    name: { jp: 'Not Sad', kr: 'Not Sad' },
    artist: 'QU4RTZ',
    year: 2021,
    alias: [],
  },
];

// LOVELIVE_NIJI_SONGS.forEach((song, idx) => {
//   if (LOVELIVE_NIJI_SONGS.slice(idx + 1).findIndex((e) => e.id === song.id) > -1) {
//     throw Error(`Duplicate ID: ${song.id}`);
//   }
// });
