import { SongEntry } from './types';

// Aliases from: https://xn--hckp3ac2l023wu2ve.com/live-music-ryakushou-matome.html
export const LOVELIVE_SUNSHINE_SONGS: SongEntry[] = [
  {
    id: 'A0001',
    name: { jp: '君のこころは輝いてるかい？', kr: '너의 마음은 빛나고 있니?' },
    artist: 'Aqours',
    year: 2015,
    alias: ['키미노 코코로와 카가야이테루카이?', '키미코코'],
  },
  {
    id: 'A0002',
    name: { jp: 'Step! ZERO to ONE', kr: 'Step! ZERO to ONE' },
    artist: 'Aqours',
    year: 2015,
    alias: ['스텝 제로 투 원', '스텝! 제로 투 원', '01', '제로원'],
  },
  {
    id: 'A0003',
    name: { jp: 'Aqours☆HEROES', kr: 'Aqours☆HEROES' },
    artist: 'Aqours',
    year: 2015,
    alias: ['아쿠아 히어로', '히로'],
  },
  {
    id: 'A0004',
    name: { jp: '恋になりたいAQUARIUM', kr: '사랑이 되고 싶은 AQUARIUM' },
    artist: 'Aqours',
    year: 2016,
    alias: ['코이니 나리타이 아쿠아리움', '코이아쿠'],
  },
  {
    id: 'A0005',
    name: { jp: '待ってて愛のうた', kr: '기다려줘 사랑의 노래' },
    artist: 'Aqours',
    year: 2016,
    alias: ['맛떼떼 아이노 우타', '맛떼아이', '맛테아이', '아이우타'],
  },
  {
    id: 'A0006',
    name: { jp: '届かない星だとしても', kr: '닿을 수 없는 별이라 해도' },
    artist: 'Aqours',
    year: 2016,
    alias: ['토도카나이 호시다토 시테모', '토도호시'],
  },
  {
    id: 'A0007',
    name: { jp: '元気全開DAY! DAY! DAY!', kr: '활기전개 DAY! DAY! DAY!' },
    artist: 'CYaRon！',
    year: 2016,
    alias: ['원기전개 DAY! DAY! DAY!', '겡키 젠카이 데이데이데이', 'DDD'],
  },
  {
    id: 'A0008',
    name: { jp: '夜空はなんでも知ってるの？', kr: '밤하늘은 뭐든지 알고 있는 거야?' },
    artist: 'CYaRon！',
    year: 2016,
    alias: ['요조라와 난데모 싯떼루노?', '요조라', '요조싯떼'],
  },
  {
    id: 'A0009',
    name: { jp: 'トリコリコPLEASE!!', kr: '토리코리코PLEASE!!' },
    artist: 'AZALEA',
    year: 2016,
    alias: ['토리코리코 플리즈!!'],
  },
  {
    id: 'A0010',
    name: { jp: 'ときめき分類学', kr: '두근거림 분류학' },
    artist: 'AZALEA',
    year: 2016,
    alias: ['토키메키'],
  },
  {
    id: 'A0011',
    name: { jp: 'Strawberry Trapper', kr: 'Strawberry Trapper' },
    artist: 'Guilty Kiss',
    year: 2016,
    alias: ['스트로베리 트래퍼', '스트토라', '스토토라', '딸기 함정꾼'],
  },
  {
    id: 'A0012',
    name: { jp: 'Guilty Night, Guilty Kiss!', kr: 'Guilty Night, Guilty Kiss!' },
    artist: 'Guilty Kiss',
    year: 2016,
    alias: ['길티 나잇, 길티 키스!', '길티 나잇 길티 키스', '길낫길키', '기루나이', 'GNGK'],
  },
  {
    id: 'A0013',
    name: { jp: '青空Jumping Heart', kr: '푸른 하늘 Jumping Heart' },
    artist: 'Aqours',
    year: 2016,
    alias: ['아오조라 점핑하트', '아오잠', '아오쟘'],
  },
  {
    id: 'A0014',
    name: { jp: 'ハミングフレンド', kr: '허밍 프렌드' },
    artist: 'Aqours',
    year: 2016,
    alias: [],
  },
  {
    id: 'A0015',
    name: { jp: 'ユメ語るよりユメ歌おう', kr: '꿈을 말하기보다 꿈을 노래하자' },
    artist: 'Aqours',
    year: 2016,
    alias: ['유메유메'],
  },
  {
    id: 'A0016',
    name: { jp: 'サンシャインぴっかぴか音頭', kr: '선샤인 반짝반짝 선창' },
    artist: 'Aqours',
    year: 2016,
    alias: ['삐까삐까'],
  },
  {
    id: 'A0017',
    name: { jp: '決めたよHand in Hand', kr: '결정했어 Hand in Hand' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우',
    year: 2016,
    alias: ['키메타요 핸드 인 핸드', '핸인핸', '키메한'],
  },
  {
    id: 'A0018',
    name: { jp: 'ダイスキだったらダイジョウブ！', kr: '정말로 좋아한다면 괜찮을 거야!' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우',
    year: 2016,
    alias: ['다이스키닷타라 다이죠부', '다이다이', '다다다'],
  },
  {
    id: 'A0019',
    name: { jp: '夢で夜空を照らしたい', kr: '꿈으로 밤하늘을 비추고 싶어' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우, 츠시마 요시코, 쿠니키다 하나마루, 쿠로사와 루비',
    year: 2016,
    alias: ['유메요조', '유메테라'],
  },
  {
    id: 'A0020',
    name: { jp: '未熟DREAMER', kr: '미숙 DREAMER' },
    artist: 'Aqours',
    year: 2016,
    alias: ['미숙 드리머'],
  },
  {
    id: 'A0021',
    name: { jp: '想いよひとつになれ', kr: '마음이여 하나가 되어라' },
    artist: '타카미 치카, 마츠우라 카난, 쿠로사와 다이아, 와타나베 요우, 츠시마 요시코, 쿠니키다 하나마루, 오하라 마리, 쿠로사와 루비',
    year: 2016,
    alias: ['오모이요 히토츠니 나레', '오모히토'],
  },
  {
    id: 'A0022',
    name: { jp: 'MIRAI TICKET', kr: 'MIRAI TICKET' },
    artist: 'Aqours',
    year: 2016,
    alias: ['미래 티켓', '미라치케'],
  },
  {
    id: 'A0023',
    name: { jp: 'Pops heartで踊るんだもん！', kr: 'Pops heart로 춤추는걸!' },
    artist: 'Aqours',
    year: 2016,
    alias: ['팝스하트'],
  },
  {
    id: 'A0024',
    name: { jp: '空も心も晴れるから', kr: '하늘도 마음도 맑을 테니까' },
    artist: '타카미 치카, 사쿠라우치 리코, 와타나베 요우',
    year: 2016,
    alias: ['소라하레'],
  },
  {
    id: 'A0025',
    name: { jp: 'Waku-Waku-Week!', kr: 'Waku-Waku-Week!' },
    artist: '츠시마 요시코, 쿠니키다 하나마루, 쿠로사와 루비',
    year: 2016,
    alias: ['와쿠와쿠위크', 'WWW'],
  },
  {
    id: 'A0026',
    name: { jp: 'Daydream Warrior', kr: 'Daydream Warrior' },
    artist: 'Aqours',
    year: 2016,
    alias: ['데이드림 워리어', '데이워리'],
  },
  {
    id: 'A0027',
    name: { jp: 'G線上のシンデレラ', kr: 'G선상의 신데렐라' },
    artist: '마츠우라 카난, 쿠로사와 다이아, 오하라 마리',
    year: 2017,
    alias: ['지선상의 신데렐라', 'G데렐라'],
  },
  {
    id: 'A0028',
    name: { jp: 'スリリング・ワンウェイ', kr: '스릴링·원 웨이' },
    artist: 'Aqours',
    year: 2017,
    alias: ['스릴링 원 웨이', '스리원'],
  },
  {
    id: 'A0029',
    name: { jp: '太陽を追いかけろ！', kr: '태양을 쫓아가자!' },
    artist: 'Aqours',
    year: 2017,
    alias: [],
  },
  {
    id: 'A0030',
    name: { jp: 'Guilty Eyes Fever', kr: 'Guilty Eyes Fever' },
    artist: 'Guilty Kiss',
    year: 2017,
    alias: ['길티 아이즈 피버'],
  },
  {
    id: 'A0031',
    name: { jp: 'P.S.の向こう側', kr: 'P.S.의 건너편' },
    artist: 'CYaRon！',
    year: 2017,
    alias: [],
  },
  {
    id: 'A0032',
    name: { jp: 'LONELY TUNING', kr: 'LONELY TUNING' },
    artist: 'AZALEA',
    year: 2017,
    alias: ['론리 튜닝'],
  },
];

// LOVELIVE_SUNSHINE_SONGS.forEach((song, idx) => {
//   if (LOVELIVE_SUNSHINE_SONGS.slice(idx + 1).findIndex((e) => e.id === song.id) > -1) {
//     throw Error(`Duplicate ID: ${song.id}`);
//   }
// });
