import { SongEntry } from './types';

// Aliases from: https://xn--hckp3ac2l023wu2ve.com/live-music-ryakushou-matome.html
export const LOVELIVE_SONGS: SongEntry[] = [
  {
    id: 'M0001',
    name: { jp: '僕らのLIVE 君とのLIFE', kr: '우리들의 LIVE 너와의 LIFE' },
    artist: 'μ\'s',
    year: 2010,
    alias: ['보쿠라노 라이브 키미토노 라이프', '우리들의 라이브 너와의 라이프', '보라라라'],
  },
  {
    id: 'M0002',
    name: { jp: '友情ノーチェンジ', kr: '우정 노 체인지' },
    artist: 'μ\'s',
    year: 2010,
    alias: ['노첸'],
  },
  {
    id: 'M0003',
    name: { jp: 'Snow halation', kr: 'Snow halation' },
    artist: 'μ\'s',
    year: 2010,
    alias: ['스노우 하레이션', '스노 하레이션', '스노하레'],
  },
  {
    id: 'M0004',
    name: { jp: 'baby maybe 恋のボタン', kr: 'baby maybe 사랑의 버튼' },
    artist: 'μ\'s',
    year: 2010,
    alias: ['베이비 메이비 코이노 보탄', '베이비 메이비 사랑의 버튼', '코이보타', '코이탄'],
  },
  {
    id: 'M0005',
    name: { jp: 'Love Marginal', kr: 'Love Marginal' },
    artist: 'Printemps',
    year: 2011,
    alias: ['러브 마지널', '러브 마지날', '러브마지'],
  },
  {
    id: 'M0006',
    name: { jp: 'sweet&sweet holiday', kr: 'sweet&sweet holiday' },
    artist: 'Printemps',
    year: 2011,
    alias: ['스윗&스윗 홀리데이', '스윗스윗 홀리데이', '스스홀', 'ssh'],
  },
  {
    id: 'M0007',
    name: { jp: 'ダイヤモンドプリンセスの憂鬱', kr: '다이아몬드 프린세스의 우울' },
    artist: 'BiBi',
    year: 2011,
    alias: ['다이프리'],
  },
  {
    id: 'M0008',
    name: { jp: 'ラブノベルス', kr: '러브 노벨즈' },
    artist: 'BiBi',
    year: 2011,
    alias: ['러브노베', '라부노베'],
  },
  {
    id: 'M0009',
    name: { jp: '知らないLove*教えてLove', kr: '모르겠어 Love*가르쳐줘 Love' },
    artist: 'lily white',
    year: 2011,
    alias: ['시라나이 Love 오시에떼 Love', '시라라라'],
  },
  {
    id: 'M0010',
    name: { jp: 'あ・の・ね・が・ん・ば・れ！', kr: '있・잖・아・힘・을・내!' },
    artist: 'lily white',
    year: 2011,
    alias: ['아노네 간바레', '아노네'],
  },
  {
    id: 'M0011',
    name: { jp: '夏色えがおで1,2,Jump!', kr: '여름빛 미소로 1,2,Jump!' },
    artist: 'μ\'s',
    year: 2011,
    alias: ['나츠이로 에가오데 원투점프!', '나츠이로'],
  },
  {
    id: 'M0012',
    name: { jp: 'Mermaid festa vol.1', kr: 'Mermaid festa vol.1' },
    artist: 'μ\'s',
    year: 2011,
    alias: ['머메이드 페스타 볼륨 1', '머메페스1', '마메페스1'],
  },
  {
    id: 'M0013',
    name: { jp: '私たちは未来の花', kr: '우리들은 미래의 꽃' },
    artist: '소노다 우미',
    year: 2011,
    alias: ['와타시타치와 미라이노 하나', '우미꽃', '와타하나'],
  },
  {
    id: 'M0014',
    name: { jp: 'スピカテリブル', kr: '스피카 테러블' },
    artist: '미나미 코토리',
    year: 2011,
    alias: ['스피카'],
  },
  {
    id: 'M0015',
    name: { jp: '愛は太陽じゃない？', kr: '사랑은 태양이 아닐까?' },
    artist: '코사카 호노카',
    year: 2012,
    alias: ['아이와 타이요오쟈 나이?', '아이타이'],
  },
  {
    id: 'M0016',
    name: { jp: 'もうひとりじゃないよ', kr: '더 이상 혼자가 아니야' },
    artist: '코사카 호노카',
    year: 2012,
    alias: ['모오 히토리쟈 나이요'],
  },
  {
    id: 'M0017',
    name: { jp: 'もぎゅっと“love”で接近中！', kr: '꼬옥 "love"로 접근 중!' },
    artist: 'μ\'s',
    year: 2012,
    alias: ['모규', '모귯또', '러브개새끼'],
  },
  {
    id: 'M0018',
    name: { jp: '愛してるばんざーい！', kr: '사랑해 만세!' },
    artist: 'μ\'s',
    year: 2012,
    alias: ['아이시떼루 반자이!', '반자이', '아이반', '아이반자'],
  },
  {
    id: 'M0019',
    name: { jp: 'Mermaid festa vol.2 ~Passionate~', kr: 'Mermaid festa vol.2 ~Passionate~' },
    artist: '코사카 호노카, 호시조라 린',
    year: 2012,
    alias: ['머메이드 페스타 볼륨 2', '머메페스2', '마메페스2'],
  },
  {
    id: 'M0020',
    name: { jp: 'Someday of my life', kr: 'Someday of my life' },
    artist: '코사카 호노카',
    year: 2012,
    alias: ['사무라이', '섬라이'],
  },
  {
    id: 'M0021',
    name: { jp: '恋のシグナルRin rin rin!', kr: '사랑의 시그널 Rin rin rin!' },
    artist: '호시조라 린',
    year: 2012,
    alias: ['린가베'],
  },
  {
    id: 'M0022',
    name: { jp: '乙女式れんあい塾', kr: '소녀식 연애 학원' },
    artist: '토죠 노조미, 야자와 니코',
    year: 2012,
    alias: ['소녀식', '지옥식'],
  },
  {
    id: 'M0023',
    name: { jp: 'まほうつかいはじめました！', kr: '마법사 시작했습니다!' },
    artist: '야자와 니코',
    year: 2012,
    alias: ['마법', '로드 오브 니코니'],
  },
  {
    id: 'M0024',
    name: { jp: '純愛レンズ', kr: '순애 렌즈' },
    artist: '토죠 노조미',
    year: 2012,
    alias: ['순애', '렌즈'],
  },
  {
    id: 'M0025',
    name: { jp: '告白日和、です！', kr: '고백하기 좋은 날, 이에요!' },
    artist: '미나미 코토리, 코이즈미 하나요',
    year: 2012,
    alias: ['고백일화'],
  },
  {
    id: 'M0026',
    name: { jp: 'ぶる~べりぃ♥とれいん', kr: '블루~베리♥트레인' },
    artist: '미나미 코토리',
    year: 2012,
    alias: ['블루베리 트레인', '트레인', '토레인', '블루토레', '브루토레', '부루토레', '블루베리'],
  },
  {
    id: 'M0027',
    name: { jp: '孤独なHeaven', kr: '고독한 Heaven' },
    artist: '코이즈미 하나요',
    year: 2012,
    alias: ['고독한 헤븐', '헤븐', '고독'],
  },
  {
    id: 'M0028',
    name: { jp: 'soldier game', kr: 'soldier game' },
    artist: '아야세 에리, 소노다 우미, 니시키노 마키',
    year: 2012,
    alias: ['소루게', '솔져 게임', '솔저 게임', '군인 놀이'],
  },
  {
    id: 'M0029',
    name: { jp: 'Daring!!', kr: 'Daring!!' },
    artist: '니시키노 마키',
    year: 2012,
    alias: ['다링!!', '달링!!'],
  },
  {
    id: 'M0030',
    name: { jp: '勇気のReason', kr: '용기의 Reason' },
    artist: '소노다 우미',
    year: 2012,
    alias: ['용기의 리즌'],
  },
  {
    id: 'M0031',
    name: { jp: 'ありふれた悲しみの果て', kr: '흔한 슬픔의 끝' },
    artist: '아야세 에리',
    year: 2012,
    alias: ['카나시미', '아리카나', '흔슬끝'],
  },
  {
    id: 'M0032',
    name: { jp: 'Wonderful Rush', kr: 'Wonderful Rush' },
    artist: 'μ\'s',
    year: 2012,
    alias: ['원더풀 러쉬', '원더풀 러시', '원더런', '비행기', '이에니카엨챸타노'],
  },
  {
    id: 'M0033',
    name: { jp: 'Oh,Love＆Peace!', kr: 'Oh,Love＆Peace!' },
    artist: 'μ\'s',
    year: 2012,
    alias: ['러브 앤 피스', '러브피'],
  },
  {
    id: 'M0034',
    name: { jp: 'Listen to my heart!!', kr: 'Listen to my heart!!' },
    artist: '호시조라 린, 코이즈미 하나요, 야자와 니코',
    year: 2012,
    alias: ['리슨 투 마이 하트!!', '리스마이', 'Ltmh'],
  },
  {
    id: 'M0035',
    name: { jp: 'after school NAVIGATORS', kr: 'after school NAVIGATORS' },
    artist: '호시조라 린, 코이즈미 하나요, 야자와 니코',
    year: 2012,
    alias: ['애프터 스쿨 내비게이터스', 'asN', '방과후'],
  },
  {
    id: 'M0036',
    name: { jp: '僕らは今のなかで', kr: '우리들은 지금 속에서' },
    artist: 'μ\'s',
    year: 2013,
    alias: ['보쿠라와 이마노 나카데', '보쿠이마'],
  },
  {
    id: 'M0037',
    name: { jp: 'WILD STARS', kr: 'WILD STARS' },
    artist: 'μ\'s',
    year: 2013,
    alias: ['와일드 스타즈', '와이스타'],
  },
  {
    id: 'M0038',
    name: { jp: 'きっと青春が聞こえる', kr: '분명 청춘이 들릴 거야' },
    artist: 'μ\'s',
    year: 2013,
    alias: ['킷토 세이슌가 키코에루'],
  },
  {
    id: 'M0039',
    name: { jp: '輝夜の城で踊りたい', kr: '카구야의 성에서 춤추고 싶어' },
    artist: 'μ\'s',
    year: 2013,
    alias: ['콜법관'],
  },
  {
    id: 'M0040',
    name: { jp: 'ススメ→トゥモロウ', kr: '나아가→Tomorrow' },
    artist: '코사카 호노카, 미나미 코토리, 소노다 우미',
    year: 2013,
    alias: ['스스메 투모로우'],
  },
  {
    id: 'M0041',
    name: { jp: 'START:DASH!!', kr: 'START:DASH!!' },
    artist: '코사카 호노카, 미나미 코토리, 소노다 우미',
    year: 2013,
    alias: ['스타트 대시!!', '스타트 대쉬!!', '스타다'],
  },
  {
    id: 'M0042',
    name: { jp: 'これからのSomeday', kr: '앞으로 다가올 Someday' },
    artist: '코사카 호노카, 미나미 코토리, 소노다 우미, 호시조라 린, 니시키노 마키, 코이즈미 하나요, 야자와 니코',
    year: 2013,
    alias: ['코레카라노 섬데이', '앞으로 다가올 섬데이', '코레섬데', '코레사무'],
  },
  {
    id: 'M0043',
    name: { jp: 'Wonder zone', kr: 'Wonder zone' },
    artist: 'μ\'s',
    year: 2013,
    alias: ['원더 존', 'WZ'],
  },
  {
    id: 'M0044',
    name: { jp: 'No brand girls', kr: 'No brand girls' },
    artist: 'μ\'s',
    year: 2013,
    alias: ['노 브랜드 걸스', '노 브랜드 걸즈', '노브라', '노브랜'],
  },
  {
    id: 'M0045',
    name: { jp: 'START:DASH!! (μ\'s)', kr: 'START:DASH!! (μ\'s)' },
    artist: 'μ\'s',
    year: 2013,
    alias: ['스타트 대시!!', '스타트 대쉬!!', '스타다'],
  },
  {
    id: 'M0046',
    name: { jp: '夢なき夢は夢じゃない', kr: '꿈이 없는 꿈은 꿈이 아니야' },
    artist: '코사카 호노카',
    year: 2013,
    alias: ['파이토다요', '유메유메유메', '꿈꿈꿈', '꿈3'],
  },
  {
    id: 'M0047',
    name: { jp: 'Anemone heart', kr: 'Anemone heart' },
    artist: '미나미 코토리, 소노다 우미',
    year: 2013,
    alias: ['아네모네 하트'],
  },
  {
    id: 'M0048',
    name: { jp: 'なわとび', kr: '줄넘기' },
    artist: '코이즈미 하나요',
    year: 2013,
    alias: ['나와토비'],
  },
  {
    id: 'M0049',
    name: { jp: 'Beat in Angel', kr: 'Beat in Angel' },
    artist: '호시조라 린, 니시키노 마키',
    year: 2013,
    alias: ['비트 인 엔젤', '빗 인 엔젤', 'BiA', '마지엔젤'],
  },
  {
    id: 'M0050',
    name: { jp: 'にこぷり♡女子道', kr: '니코프리♡여자의 길' },
    artist: '야자와 니코',
    year: 2013,
    alias: ['니코프리 니코니코'],
  },
  {
    id: 'M0051',
    name: { jp: '硝子の花園', kr: '유리의 화원' },
    artist: '아야세 에리, 토죠 노조미',
    year: 2013,
    alias: ['살메히망', '노조에리'],
  },
  {
    id: 'M0052',
    name: { jp: 'LONELIEST BABY', kr: 'LONELIEST BABY' },
    artist: 'μ\'s',
    year: 2013,
    alias: ['론리스트 베이비', 'LB'],
  },
  {
    id: 'M0053',
    name: { jp: 'ぷわぷわーお！', kr: '푹신푹신-오!' },
    artist: 'Printemps',
    year: 2013,
    alias: ['뿌와뿌와오', '푸와푸와오', '후시기다요', '키미니 톤데케 스키스키 뿌와뿌와'],
  },
];
